# Generated by Django 5.2.17 on 2026-10-03 11:35

import django.db.models.deletion
import services.segments.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0013_totp_device"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Segment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "description",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("customer", "Organisations"),
                            ("account", "Accounts"),
                            ("contact", "Contacts"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "rules",
                    models.JSONField(
                        default=services.segments.models.default_rules,
                        help_text="Rule JSON; see services/segments/registry.py.",
                    ),
                ),
                (
                    "pinned_ids",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Records kept in, whatever the rules say.",
                    ),
                ),
                (
                    "excluded_ids",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Records kept out, whatever the rules say.",
                    ),
                ),
                (
                    "sharing",
                    models.CharField(
                        choices=[
                            ("private", "Only me"),
                            ("workspace", "Everyone in the workspace"),
                            ("people", "Chosen teammates"),
                        ],
                        default="private",
                        max_length=16,
                    ),
                ),
                ("alert_on_changes", models.BooleanField(default=False)),
                (
                    "paused",
                    models.BooleanField(
                        default=False,
                        help_text="Set by the nightly step while the owner is inactive; evaluation stops.",
                    ),
                ),
                (
                    "last_members",
                    models.JSONField(
                        blank=True,
                        help_text="Sorted member ids at the last nightly evaluation, as the owner saw them. Null before the first one, and for a segment too large to track.",
                        null=True,
                    ),
                ),
                ("member_count", models.PositiveIntegerField(blank=True, null=True)),
                ("last_evaluated_on", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="segments",
                        to="accounts.organisation",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="segments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "shared_with",
                    models.ManyToManyField(
                        blank=True,
                        related_name="shared_segments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name", "id"],
            },
        ),
        migrations.CreateModel(
            name="SegmentChange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("record_id", models.PositiveBigIntegerField()),
                (
                    "change",
                    models.CharField(
                        choices=[("entered", "Entered"), ("left", "Left")], max_length=8
                    ),
                ),
                ("changed_on", models.DateField()),
                ("reason", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "segment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="changes",
                        to="segments.segment",
                    ),
                ),
            ],
            options={
                "ordering": ["-changed_on", "-id"],
            },
        ),
        migrations.AddIndex(
            model_name="segment",
            index=models.Index(
                fields=["organisation", "sharing"],
                name="segments_se_organis_4e651f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="segmentchange",
            index=models.Index(
                fields=["segment", "changed_on"], name="segments_se_segment_129859_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="segmentchange",
            constraint=models.UniqueConstraint(
                fields=("segment", "record_id", "changed_on"),
                name="one_segment_change_per_record_per_day",
            ),
        ),
    ]
