# Generated by Django 5.2.17 on 2026-09-04 13:53

import django.db.models.deletion
import services.webhooks.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0003_organisation_ai_agent_enabled_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="WebhookSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(max_length=500)),
                (
                    "event",
                    models.CharField(
                        choices=[("customer.created", "Organization Created")],
                        max_length=32,
                    ),
                ),
                (
                    "secret",
                    models.CharField(
                        default=services.webhooks.models._generate_secret,
                        editable=False,
                        max_length=64,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="webhooks",
                        to="accounts.organisation",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WebhookDelivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("success", models.BooleanField()),
                ("status_code", models.IntegerField(blank=True, null=True)),
                ("error", models.CharField(blank=True, max_length=255)),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                (
                    "webhook",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliveries",
                        to="webhooks.webhooksubscription",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "webhook deliveries",
                "ordering": ["-sent_at"],
            },
        ),
    ]
