# Generated by Django 5.2.17 on 2026-09-04 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("customers", "0017_remove_account_customer"),
    ]

    operations = [
        migrations.CreateModel(
            name="Scenario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="Untitled Scenario", max_length=255)),
                (
                    "apply_to",
                    models.CharField(
                        choices=[
                            ("organizations", "Organizations"),
                            ("accounts", "Accounts"),
                            ("contacts", "Contacts"),
                        ],
                        default="organizations",
                        max_length=16,
                    ),
                ),
                ("nodes", models.JSONField(blank=True, default=list)),
                ("edges", models.JSONField(blank=True, default=list)),
                (
                    "is_active",
                    models.BooleanField(
                        default=False,
                        help_text="Gates On Event auto-execution (see scenarios.signals). Run Now ignores this — it's an explicit, one-off ask.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scenarios",
                        to="accounts.organisation",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="ScenarioRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "triggered_by",
                    models.CharField(
                        choices=[("manual", "Manual"), ("event", "Event")], max_length=8
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("success", "Success"), ("failed", "Failed")],
                        default="success",
                        max_length=8,
                    ),
                ),
                ("log", models.JSONField(blank=True, default=list)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="scenario_runs",
                        to="customers.customer",
                    ),
                ),
                (
                    "scenario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="runs",
                        to="scenarios.scenario",
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
    ]
