# Generated by Django 5.2.17 on 2026-09-10 10:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("copilot", "0002_copilotsession_sessionevent_sessioninvite_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="sources",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Assistant turns only: the records this answer was built from, as snapshots — see services/copilot/retrieval.py's _source_ref for why a snapshot rather than a foreign key. Empty on user turns, and on assistant turns where retrieval found nothing to quote.",
            ),
        ),
    ]
