# Generated by Django 5.2.17 on 2026-09-12 17:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0007_grant_view_all_accounts"),
        ("copilot", "0003_message_sources"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ModelBudget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("purpose", models.CharField(max_length=32)),
                (
                    "monthly_tokens",
                    models.PositiveIntegerField(
                        help_text="Input plus output tokens, per calendar month."
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="model_budgets",
                        to="accounts.organisation",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organisation", "purpose"),
                        name="modelbudget_one_per_purpose",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ModelCall",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "purpose",
                    models.CharField(
                        help_text='"copilot", "headlines", "classification", "brief", "proposals".',
                        max_length=32,
                    ),
                ),
                ("provider", models.CharField(blank=True, max_length=16)),
                ("model", models.CharField(blank=True, max_length=128)),
                ("input_tokens", models.PositiveIntegerField(default=0)),
                ("output_tokens", models.PositiveIntegerField(default=0)),
                ("max_tokens", models.PositiveIntegerField(default=0)),
                ("latency_ms", models.PositiveIntegerField(default=0)),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("ok", "OK"),
                            ("failed", "Failed"),
                            ("unconfigured", "Not configured"),
                            ("over_budget", "Over budget"),
                        ],
                        max_length=16,
                    ),
                ),
                ("error", models.CharField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organisation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="model_calls",
                        to="accounts.organisation",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["organisation", "purpose", "created_at"],
                        name="copilot_mod_organis_c3b271_idx",
                    )
                ],
            },
        ),
    ]
