# Generated by Django 5.2.17 on 2026-09-12 18:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("copilot", "0004_model_calls_and_budgets"),
    ]

    operations = [
        migrations.AlterField(
            model_name="modelcall",
            name="purpose",
            field=models.CharField(
                help_text='"copilot", "headlines", "classification", "brief", "proposals", "facilitator".',
                max_length=32,
            ),
        ),
    ]
