# Generated by Django 5.2.17 on 2026-09-12 21:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("copilot", "0005_proposal_session"),
    ]

    operations = [
        migrations.AlterField(
            model_name="modelcall",
            name="purpose",
            field=models.CharField(
                help_text="A key in services.copilot.usage.PURPOSES — one per skill.",
                max_length=32,
            ),
        ),
    ]
