# Generated by Django 5.2.17 on 2026-09-12 21:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("copilot", "0006_questions"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="ask_suggestions",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Assistant turns only: the people responsible for the customer the question was about, as {user_id, name, function, function_display, customer_id, customer_name} — so the screen can offer 'ask Mei' in one click when the answer runs out (services.knowledge). A snapshot of who was responsible when the answer was given.",
            ),
        ),
    ]
