# Generated by Django 5.2.17 on 2026-09-12 22:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("copilot", "0007_ask_suggestions"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="author",
            field=models.ForeignKey(
                blank=True,
                help_text="User turns: who wrote it — the owner, or a participant. Null on assistant turns. What a mentioned person may see of a conversation is decided per turn from this (services.accounts.hierarchy).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="copilot_messages",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
