# Generated by Django 5.2.17 on 2026-09-24 11:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("copilot", "0009_backfill_message_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="origin",
            field=models.JSONField(
                blank=True,
                help_text="Where the conversation started on the Dashboard: the first dashboard message's context without its focus ({surface, area, view, filters}). Set once, never overwritten. Null for a conversation that never had a dashboard message. Ids and filter values only.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="context",
            field=models.JSONField(
                blank=True,
                help_text="User turns asked on the Dashboard: the validated screen context ({surface, area, view, filters, focus}) after the focus was intersected with the asker's filtered book (services/copilot/dashboard_context.py). Ids and filter values only, never record text. Null on every other turn.",
                null=True,
            ),
        ),
    ]
