# Generated by Django 5.2.17 on 2026-09-24 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("copilot", "0010_dashboard_context"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="reply_to",
            field=models.ForeignKey(
                blank=True,
                help_text="Assistant turns only: the user turn this reply answers, set by SendMessageView at creation time. Ordering (created_at, id) alone can't be trusted to pair a reply with its question — two participants sending concurrently can interleave a second user turn between a reply and the one it actually answers (services.copilot.views._reply_readable_by's own docstring) — so redaction and history use this FK when it is set, falling back to the immediately preceding user turn only for legacy rows with none.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="replies",
                to="copilot.message",
            ),
        ),
    ]
