# Generated by Django 5.2.17 on 2026-09-26 10:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("copilot", "0012_ask_surfaces"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="grounded_customer_ids",
            field=models.JSONField(
                blank=True,
                help_text="Assistant turns answering an Ask rail (Dashboard or Organizations) only: the ids of every customer the grounding digest could have drawn on, fixed when the answer was written (Grounding.customer_ids). A mentioned-only reader reads the reply only if they may see every one of them (views._reply_readable_by). Ids only, never names. Null on every other turn, and on Ask replies written before it existed, which then fail closed for such readers.",
                null=True,
            ),
        ),
    ]
