# Generated by Django 5.2.17 on 2026-09-26 11:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("copilot", "0012_ask_surfaces"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="carries_anomaly_text",
            field=models.BooleanField(
                blank=True,
                help_text="Assistant turns answering an Ask rail only, fixed when the answer was written: True when it could carry a stored, org-wide anomaly title or summary — its own turn was anomaly-shaped (Overview, or an anomaly attention focus) and the asker then saw every account, or an earlier reply fed to it as history could. A reader who does not see every account never reads such a reply. Null (a reply written before it existed) is read as True.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="grounded_customer_ids",
            field=models.JSONField(
                blank=True,
                help_text="Assistant turns answering an Ask rail (Dashboard or Organizations) only: the ids of every customer the grounding digest could have drawn on, fixed when the answer was written (Grounding.customer_ids). A mentioned-only reader reads the reply only if they may see every one of them (views._reply_readable_by). Ids only, never names. Null on every other turn, on Ask replies written before it existed, and on an Ask reply fed an earlier Ask reply with none as history; all of those fail closed for such readers. Includes the ids of every earlier Ask reply fed to the model as history.",
                null=True,
            ),
        ),
    ]
