# Generated by Django 5.2.17 on 2026-09-27 07:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("copilot", "0015_mark_legacy_followups"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="grounded_pipeline",
            field=models.JSONField(
                blank=True,
                help_text="Assistant turns answering an Ask rail, or fed one as history, only: {account_ids, departments} of the open opportunities and risks the digest's figures counted (forecast.counted_pipeline), fixed when the answer was written; empty lists when it counted none. A mentioned-only reader reads the reply only if they could list every one (views._reply_readable_by). Ids and department codes only. Null on every other turn and on replies written before it existed; such a reply fails closed for those readers when it could have carried pipeline (a Dashboard Overview or Revenue reply, or one fed an Ask reply).",
                null=True,
            ),
        ),
    ]
