# Generated by Django 5.2.17 on 2026-09-27 08:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("copilot", "0016_message_grounded_pipeline"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="grounded_tickets",
            field=models.JSONField(
                blank=True,
                help_text="Assistant turns answering an Ask rail, or fed one as history, only: {account_ids, departments} of the tickets the digest's figures counted (personal.ticket_snapshot), fixed when the answer was written; empty lists when it counted none. A mentioned-only reader needs every department readable under the ticket rule (Leadership only is exempt) and, unless they see every account, every account in their visible accounts (views._reply_readable_by). Null on every other turn and on replies written before it existed; such a reply fails closed for those readers when it could have counted tickets (a Dashboard Overview or Support reply, a support attention focus, or one fed an Ask reply).",
                null=True,
            ),
        ),
    ]
