# Generated by Django 5.2.17 on 2026-09-28 04:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("copilot", "0017_message_grounded_tickets"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="grounded_records",
            field=models.JSONField(
                blank=True,
                help_text="Assistant turns answering an Ask rail, or fed one as history, only: references ({type, id, company_type, company_id}) to the records the digest quoted or counted without citing them — an organisation page's story items, its focus and the accounts it covered (Grounding.records) — fixed when the answer was written; empty when it quoted none. A mentioned-only reader is checked against each exactly as against sources (views._reply_readable_by). References only, never text. Null on every other turn and on replies written before it existed; an organisation page reply with none fails closed.",
                null=True,
            ),
        ),
    ]
