# Generated by Django 5.2.17 on 2026-09-12 21:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="kind",
            field=models.CharField(
                choices=[
                    ("copilot_invite", "Copilot invite"),
                    ("copilot_handoff", "Copilot hand-off"),
                    ("customer_assigned", "Customer assigned"),
                    ("account_assigned", "Account assigned"),
                    ("question_asked", "Question asked"),
                    ("question_answered", "Question answered"),
                ],
                max_length=20,
            ),
        ),
    ]
