# Generated by Django 5.2.17 on 2026-09-16 10:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0010_global_attributes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MailboxConnection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("google", "Google Workspace / Gmail"),
                            ("microsoft", "Microsoft 365 / Outlook"),
                            ("imap", "IMAP / SMTP"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "address",
                    models.EmailField(
                        help_text="The mailbox's own address, as the provider reports it.",
                        max_length=254,
                    ),
                ),
                ("display_name", models.CharField(blank=True, max_length=150)),
                ("credentials", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("connected", "Connected"),
                            ("error", "Needs attention"),
                        ],
                        default="connected",
                        max_length=16,
                    ),
                ),
                ("error", models.CharField(blank=True, max_length=255)),
                ("sync_cursor", models.CharField(blank=True, max_length=512)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mailboxes",
                        to="accounts.organisation",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mailbox",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
