# Generated by Django 5.2.17 on 2026-09-21 18:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0013_totp_device"),
        ("customers", "0046_email_thread_index"),
        ("mail", "0001_mailbox"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MailMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("provider_message_id", models.CharField(max_length=255)),
                ("thread_id", models.CharField(blank=True, max_length=255)),
                (
                    "direction",
                    models.CharField(
                        choices=[("sent", "Sent"), ("received", "Received")],
                        max_length=8,
                    ),
                ),
                ("from_name", models.CharField(blank=True, max_length=150)),
                ("from_address", models.EmailField(blank=True, max_length=254)),
                (
                    "to",
                    models.JSONField(blank=True, default=list, help_text="[[name, address], ...]"),
                ),
                ("subject", models.CharField(max_length=255)),
                ("snippet", models.CharField(blank=True, max_length=300)),
                ("body", models.TextField(blank=True)),
                ("sent_at", models.DateTimeField()),
                (
                    "folder",
                    models.CharField(
                        choices=[
                            ("inbox", "Inbox"),
                            ("sent", "Sent"),
                            ("drafts", "Drafts"),
                            ("spam", "Spam"),
                            ("trash", "Trash"),
                        ],
                        default="inbox",
                        max_length=8,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("general", "General"),
                            ("financial", "Financial"),
                            ("newsletters", "Newsletters"),
                            ("notifications", "Notifications"),
                            ("promotions", "Promotions"),
                            ("social", "Social"),
                        ],
                        default="general",
                        max_length=16,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("done", "Done"),
                            ("muted", "Muted"),
                        ],
                        default="open",
                        max_length=8,
                    ),
                ),
                ("is_read", models.BooleanField(default=True)),
                ("is_starred", models.BooleanField(default=False)),
                ("is_important", models.BooleanField(default=False)),
                ("synced_at", models.DateTimeField(auto_now_add=True)),
                (
                    "connection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="mail.mailboxconnection",
                    ),
                ),
                (
                    "email",
                    models.OneToOneField(
                        blank=True,
                        help_text="The filed copy, when the message matched someone in the book.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mail_message",
                        to="customers.email",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mail_messages",
                        to="accounts.organisation",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mail_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-sent_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["owner", "folder", "state", "-sent_at"],
                        name="mail_mailme_owner_i_567263_idx",
                    ),
                    models.Index(
                        fields=["owner", "category"],
                        name="mail_mailme_owner_i_b796a4_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("connection", "provider_message_id"),
                        name="mail_message_once_per_mailbox",
                    )
                ],
            },
        ),
    ]
