# Generated by Django 5.2.17 on 2026-09-04 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0003_organisation_ai_agent_enabled_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FxRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("USD", "US Dollar ($)"),
                            ("EUR", "Euro (€)"),
                            ("GBP", "British Pound (£)"),
                            ("INR", "Indian Rupee (₹)"),
                            ("CAD", "Canadian Dollar (C$)"),
                            ("AUD", "Australian Dollar (A$)"),
                            ("JPY", "Japanese Yen (¥)"),
                        ],
                        max_length=3,
                    ),
                ),
                (
                    "rate_to_org_currency",
                    models.DecimalField(
                        decimal_places=6,
                        help_text="How many units of the org's own currency equal 1 unit of `currency`. FX rates need more precision than money amounts do, hence 6 decimal places rather than the usual 2.",
                        max_digits=12,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fx_rates",
                        to="accounts.organisation",
                    ),
                ),
            ],
            options={
                "ordering": ["currency"],
                "unique_together": {("organisation", "currency")},
            },
        ),
    ]
