# Generated by Django 5.2.17 on 2026-09-12 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0007_grant_view_all_accounts"),
    ]

    operations = [
        migrations.CreateModel(
            name="MetricSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "metric",
                    models.CharField(
                        help_text="A key from services.metrics.registry.", max_length=64
                    ),
                ),
                (
                    "dimension",
                    models.CharField(
                        blank=True,
                        help_text='Empty for the whole organisation; later "owner", "product", ...',
                        max_length=32,
                    ),
                ),
                (
                    "member",
                    models.CharField(
                        blank=True,
                        help_text="The dimension member's id or value; empty for whole-org.",
                        max_length=64,
                    ),
                ),
                (
                    "period_end",
                    models.DateField(help_text="The last day of the month this row describes."),
                ),
                (
                    "value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Null when the metric could not be measured that month — not zero.",
                        max_digits=18,
                        null=True,
                    ),
                ),
                ("captured_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metric_snapshots",
                        to="accounts.organisation",
                    ),
                ),
            ],
            options={
                "ordering": ["metric", "period_end"],
                "indexes": [
                    models.Index(
                        fields=["organisation", "metric", "period_end"],
                        name="metrics_met_organis_cff422_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "organisation",
                            "metric",
                            "dimension",
                            "member",
                            "period_end",
                        ),
                        name="metricsnapshot_one_per_metric_member_period",
                    )
                ],
            },
        ),
    ]
