# Generated by Django 5.2.17 on 2026-09-12 16:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_grant_view_all_accounts"),
        ("metrics", "0001_metric_snapshot"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Brief",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("as_of", models.DateField(help_text="The day the figures describe.")),
                (
                    "baseline",
                    models.DateField(
                        blank=True,
                        help_text="The month-end the figures were compared against, if any.",
                        null=True,
                    ),
                ),
                ("headline", models.CharField(max_length=255)),
                (
                    "body",
                    models.TextField(help_text="Paragraphs separated by blank lines."),
                ),
                (
                    "watch",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="2-4 things to watch next month.",
                    ),
                ),
                (
                    "evidence",
                    models.JSONField(
                        help_text="What the model was given — the figures, verbatim."
                    ),
                ),
                ("generated_at", models.DateTimeField()),
                (
                    "generated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="briefs",
                        to="accounts.organisation",
                    ),
                ),
            ],
            options={
                "ordering": ["-generated_at"],
            },
        ),
    ]
