# Generated by Django 5.2.17 on 2026-09-12 17:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0007_grant_view_all_accounts"),
        ("metrics", "0003_initiative"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Proposal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "batch",
                    models.CharField(
                        help_text="One generation run; proposals share it.",
                        max_length=32,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("task", "Task on an account"),
                            ("initiative", "Initiative"),
                        ],
                        max_length=16,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "rationale",
                    models.TextField(help_text="Why, in the agent's words, citing the evidence."),
                ),
                (
                    "evidence",
                    models.JSONField(
                        default=list,
                        help_text="The figures cited, as given to the agent.",
                    ),
                ),
                (
                    "action",
                    models.JSONField(
                        help_text="Exactly what approving does, validated at generation."
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("proposed", "Proposed"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="proposed",
                        max_length=16,
                    ),
                ),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("decision_note", models.TextField(blank=True)),
                (
                    "result",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="What approval created, e.g. a task id.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "generated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "initiative",
                    models.ForeignKey(
                        blank=True,
                        help_text="The open initiative this serves, if the agent linked one.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="proposals",
                        to="metrics.initiative",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proposals",
                        to="accounts.organisation",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
