# Generated by Django 5.2.17 on 2026-09-12 17:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0007_grant_view_all_accounts"),
        ("metrics", "0004_proposal"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("classification", "Classification corrected"),
                            ("proposal", "Proposal decided"),
                            ("health_override", "Health score overridden"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "subject_type",
                    models.CharField(
                        help_text='"ticket", "email", "call", "customer", "proposal".',
                        max_length=32,
                    ),
                ),
                ("subject_id", models.PositiveIntegerField()),
                (
                    "subject_label",
                    models.CharField(
                        help_text="What the row was about, as it read then.",
                        max_length=255,
                    ),
                ),
                (
                    "before",
                    models.JSONField(default=dict, help_text="What the system said."),
                ),
                (
                    "after",
                    models.JSONField(default=dict, help_text="What the person said."),
                ),
                ("note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "made_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedback",
                        to="accounts.organisation",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["organisation", "kind", "created_at"],
                        name="metrics_fee_organis_cc193d_idx",
                    )
                ],
            },
        ),
    ]
