# Generated by Django 5.2.17 on 2026-09-12 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("copilot", "0005_proposal_session"),
        ("metrics", "0005_feedback_and_corrections"),
    ]

    operations = [
        migrations.AddField(
            model_name="proposal",
            name="session",
            field=models.ForeignKey(
                blank=True,
                help_text="Set when the facilitator wrote this from a multiplayer session's decisions rather than the Ops agent from the figures alone.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="proposals",
                to="copilot.copilotsession",
            ),
        ),
    ]
