# Generated by Django 5.2.17 on 2026-09-12 18:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0007_grant_view_all_accounts"),
        ("metrics", "0006_proposal_session"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Explanation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "metric",
                    models.CharField(help_text="A key in the metric registry.", max_length=64),
                ),
                ("as_of", models.DateField(help_text="The day the figures describe.")),
                (
                    "baseline",
                    models.DateField(
                        blank=True,
                        help_text="The month-end the figures were compared against, if any.",
                        null=True,
                    ),
                ),
                (
                    "value",
                    models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True),
                ),
                (
                    "previous_value",
                    models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True),
                ),
                ("text", models.TextField()),
                (
                    "evidence",
                    models.JSONField(blank=True, default=list, help_text="The figures cited."),
                ),
                (
                    "inputs",
                    models.JSONField(help_text="What the model was given — the figures, verbatim."),
                ),
                ("generated_at", models.DateTimeField()),
                (
                    "generated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="explanations",
                        to="accounts.organisation",
                    ),
                ),
            ],
            options={
                "ordering": ["-generated_at"],
                "indexes": [
                    models.Index(
                        fields=["organisation", "metric", "-generated_at"],
                        name="metrics_exp_organis_cbe158_idx",
                    )
                ],
            },
        ),
    ]
