# Generated by Django 5.2.17 on 2026-09-23 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0013_totp_device"),
    ]

    operations = [
        migrations.CreateModel(
            name="Translation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("ticket", "Ticket"),
                            ("call", "Call"),
                            ("mail_message", "Mailbox message"),
                        ],
                        max_length=16,
                    ),
                ),
                ("record_id", models.PositiveIntegerField()),
                ("language", models.CharField(max_length=12)),
                (
                    "detected_language",
                    models.CharField(blank=True, default="", max_length=12),
                ),
                ("text", models.TextField()),
                ("source_hash", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="accounts.organisation",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("kind", "record_id", "language"),
                        name="one_translation_per_record_per_language",
                    )
                ],
            },
        ),
    ]
