# Generated by Django 5.2.17 on 2026-09-10 03:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0007_grant_view_all_accounts"),
        ("customers", "0023_headline"),
    ]

    operations = [
        migrations.CreateModel(
            name="Connector",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("zendesk", "Zendesk"),
                            ("jira", "Jira Software"),
                            ("intercom", "Intercom"),
                            ("salesforce", "Salesforce"),
                            ("hubspot", "HubSpot"),
                            ("slack", "Slack"),
                            ("gmail", "Gmail"),
                            ("ms_teams", "Microsoft Teams"),
                            ("github", "GitHub"),
                            ("figma", "Figma"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text='Distinguishes two of the same provider, e.g. "Zendesk (EU)" alongside "Zendesk (US)".',
                        max_length=100,
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="A disabled connector keeps its tickets and its history — it just stops being offered as somewhere new records can come from.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "accounts",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Leave empty to cover every account in the organisation.",
                        related_name="connectors",
                        to="customers.account",
                    ),
                ),
                (
                    "customers",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Leave empty to cover every customer in the organisation.",
                        related_name="connectors",
                        to="customers.customer",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="connectors",
                        to="accounts.organisation",
                    ),
                ),
            ],
            options={
                "ordering": ["provider", "name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organisation", "provider", "name"),
                        name="unique_connector_name_per_provider_per_organisation",
                    )
                ],
            },
        ),
    ]
