# Generated by Django 5.2.17 on 2026-09-12 08:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("connectors", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="connector",
            name="provider",
            field=models.CharField(
                choices=[
                    ("zendesk", "Zendesk"),
                    ("jira", "Jira Software"),
                    ("intercom", "Intercom"),
                    ("salesforce", "Salesforce"),
                    ("hubspot", "HubSpot"),
                    ("slack", "Slack"),
                    ("gmail", "Gmail"),
                    ("ms_teams", "Microsoft Teams"),
                    ("zoom", "Zoom"),
                    ("github", "GitHub"),
                    ("figma", "Figma"),
                ],
                max_length=32,
            ),
        ),
    ]
