# Generated by Django 5.2.17 on 2026-09-16 14:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("connectors", "0002_alter_connector_provider"),
    ]

    operations = [
        migrations.AddField(
            model_name="connector",
            name="config",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="connector",
            name="credentials",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="connector",
            name="department",
            field=models.CharField(
                blank=True,
                choices=[
                    ("cs", "Customer Success"),
                    ("engineering", "Engineering"),
                    ("sales", "Sales"),
                    ("analytics", "Analytics"),
                    ("leadership", "Leadership"),
                    ("other", "Other"),
                ],
                default="",
                help_text="Whose tickets these are. Blank means the whole company may read them.",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="connector",
            name="error",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="connector",
            name="last_sync_note",
            field=models.CharField(
                blank=True,
                default="",
                help_text='What the last pass did, e.g. "3 new, 2 updated, 1 without a matching account".',
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="connector",
            name="last_synced_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="connector",
            name="status",
            field=models.CharField(
                choices=[
                    ("not_connected", "Not connected"),
                    ("connected", "Connected"),
                    ("error", "Needs attention"),
                ],
                default="not_connected",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="connector",
            name="sync_cursor",
            field=models.CharField(blank=True, default="", max_length=512),
        ),
        migrations.AlterField(
            model_name="connector",
            name="provider",
            field=models.CharField(
                choices=[
                    ("zendesk", "Zendesk"),
                    ("jira", "Jira Software"),
                    ("freshdesk", "Freshdesk"),
                    ("webhook", "Any other system (webhook)"),
                    ("intercom", "Intercom"),
                    ("salesforce", "Salesforce"),
                    ("hubspot", "HubSpot"),
                    ("slack", "Slack"),
                    ("gmail", "Gmail"),
                    ("ms_teams", "Microsoft Teams"),
                    ("zoom", "Zoom"),
                    ("github", "GitHub"),
                    ("figma", "Figma"),
                ],
                max_length=32,
            ),
        ),
    ]
