# Generated by Django 5.2.17 on 2026-09-12 21:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0008_knowledge"),
        ("customers", "0035_task_initiative"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Contribution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "function",
                    models.CharField(
                        choices=[
                            ("cs", "Customer Success"),
                            ("engineering", "Engineering"),
                            ("sales", "Sales"),
                            ("analytics", "Analytics"),
                            ("leadership", "Leadership"),
                            ("other", "Other"),
                        ],
                        help_text="The author's function when they wrote this — a snapshot, so a later move between teams does not relabel what they knew then.",
                        max_length=16,
                    ),
                ),
                ("body", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contributions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contributions",
                        to="customers.customer",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contributions",
                        to="accounts.organisation",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["customer", "-created_at"],
                        name="knowledge_c_custome_887c20_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="FunctionOwner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "function",
                    models.CharField(
                        choices=[
                            ("cs", "Customer Success"),
                            ("engineering", "Engineering"),
                            ("sales", "Sales"),
                            ("analytics", "Analytics"),
                            ("leadership", "Leadership"),
                            ("other", "Other"),
                        ],
                        max_length=16,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="function_owners",
                        to="customers.customer",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="function_ownerships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("customer", "function"),
                        name="one_owner_per_function_per_customer",
                    )
                ],
            },
        ),
    ]
