# Generated by Django 5.2.17 on 2026-09-12 21:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("knowledge", "0002_questions"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="last_nudged_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the assignee was last reminded — see aging.py.",
                null=True,
            ),
        ),
    ]
