# Generated by Django 5.2.17 on 2026-09-23 05:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0013_totp_device"),
        ("customers", "0046_email_thread_index"),
        ("knowledge", "0003_last_nudged"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountBrief",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("use_cases", models.JSONField(blank=True, default=list)),
                ("stakeholders", models.JSONField(blank=True, default=list)),
                ("open_threads", models.JSONField(blank=True, default=list)),
                ("sources", models.JSONField(blank=True, default=list)),
                ("generated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="brief",
                        to="customers.customer",
                    ),
                ),
                (
                    "generated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="KnowledgeGap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(max_length=500)),
                ("fingerprint", models.CharField(max_length=500)),
                (
                    "function",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("cs", "Customer Success"),
                            ("engineering", "Engineering"),
                            ("sales", "Sales"),
                            ("analytics", "Analytics"),
                            ("leadership", "Leadership"),
                            ("other", "Other"),
                        ],
                        default="",
                        max_length=16,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("copilot", "Asked the Copilot"),
                            ("question", "Routed question went unanswered"),
                        ],
                        default="copilot",
                        max_length=16,
                    ),
                ),
                ("times_asked", models.PositiveIntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("filled", "Filled"),
                            ("dismissed", "Dismissed"),
                        ],
                        default="open",
                        max_length=16,
                    ),
                ),
                ("first_asked_at", models.DateTimeField(auto_now_add=True)),
                ("last_asked_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assignee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="knowledge_gaps",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="knowledge_gaps",
                        to="customers.customer",
                    ),
                ),
                (
                    "filled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="knowledge.contribution",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="knowledge_gaps",
                        to="accounts.organisation",
                    ),
                ),
                (
                    "question",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gap",
                        to="knowledge.question",
                    ),
                ),
            ],
            options={
                "ordering": ["-times_asked", "-last_asked_at"],
                "indexes": [
                    models.Index(
                        fields=["organisation", "status", "-times_asked"],
                        name="knowledge_k_organis_237245_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("customer", "fingerprint"),
                        name="one_open_gap_per_question_per_customer",
                    )
                ],
            },
        ),
    ]
