# Generated by Django 5.2.17 on 2026-09-23 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("knowledge", "0004_gaps_and_brief"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="gap_raised_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="knowledgegap",
            name="question",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="raised_gaps",
                to="knowledge.question",
            ),
        ),
    ]
