# Generated by Django 5.2.17 on 2026-09-01 08:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0002_remove_customer_arr_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="is_archived",
            field=models.BooleanField(
                default=False,
                help_text="Soft-hide from the default list/stats/renewal views without deleting. Distinct from lifecycle_stage=churn — archiving is 'stop showing me this', churning is a business outcome.",
            ),
        ),
    ]
