# Generated by Django 5.2.17 on 2026-09-02 07:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0003_customer_is_archived"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "domain",
                    models.CharField(
                        blank=True,
                        help_text="Falls back to the parent customer's domain (for the logo) when blank.",
                        max_length=255,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "lifecycle_stage",
                    models.CharField(
                        choices=[
                            ("onboarding", "Onboarding"),
                            ("kickoff", "Kickoff"),
                            ("adoption", "Adoption"),
                            ("live", "Live"),
                            ("renewal", "Renewal"),
                            ("churn", "Churn"),
                            ("expansion", "Expansion"),
                            ("other", "Other"),
                        ],
                        default="onboarding",
                        max_length=20,
                    ),
                ),
                (
                    "health_score",
                    models.DecimalField(
                        decimal_places=1,
                        default=5.0,
                        help_text="0.0-10.0. health_category is derived from this, not stored.",
                        max_digits=3,
                    ),
                ),
                (
                    "pulse",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Recent pulse-history dots, e.g. [1,1,0,2,1].",
                    ),
                ),
                (
                    "ai_pulse_score",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("very_satisfied", "Very Satisfied"),
                            ("satisfied", "Satisfied"),
                            ("moderate", "Moderate"),
                            ("high_risk", "High Risk"),
                        ],
                        max_length=20,
                    ),
                ),
                ("ai_pulse_reason", models.TextField(blank=True)),
                (
                    "nps_score",
                    models.IntegerField(
                        blank=True, help_text="-100 to 100.", null=True
                    ),
                ),
                (
                    "csat_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="0-100 (%).",
                        max_digits=5,
                        null=True,
                    ),
                ),
                ("renewal_date", models.DateField(blank=True, null=True)),
                (
                    "arr",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="MRR is derived (arr / 12) rather than stored, same as Customer.",
                        max_digits=12,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accounts",
                        to="customers.customer",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        help_text="The CSM (or admin) assigned to this account. Must be in the same organisation.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owned_accounts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
