# Generated by Django 5.2.17 on 2026-09-02 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0004_account"),
    ]

    operations = [
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("value_reinforcement", "Value Reinforcement"),
                            ("enablement_retraining", "Enablement or Re-Training"),
                            ("health_check_review", "Health Check Review"),
                            ("product_usage_analysis", "Product Usage Analysis"),
                            ("escalation_triggered", "Escalation Triggered"),
                            ("onboarding_milestone", "Onboarding Milestone Reached"),
                            ("success_plan_created", "Success Plan Created"),
                            ("success_plan_updated", "Success Plan Updated"),
                            (
                                "executive_alignment_session",
                                "Executive Alignment Session",
                            ),
                            (
                                "renewal_proposal_submitted",
                                "Renewal Proposal Submitted",
                            ),
                            ("other", "Other"),
                        ],
                        max_length=32,
                    ),
                ),
                ("occurred_at", models.DateField()),
                (
                    "links",
                    models.PositiveIntegerField(
                        default=0, help_text="Count shown on the card's link icon."
                    ),
                ),
                (
                    "watchers",
                    models.PositiveIntegerField(
                        default=0, help_text="Count shown on the card's eye icon."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "account",
                    models.ForeignKey(
                        blank=True,
                        help_text="Set for an account-level activity. Exactly one of customer/account is set, never both — see the model's own CheckConstraint.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="customers.account",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        help_text="Set for an organization-level activity. Exactly one of customer/account is set, never both — see the model's own CheckConstraint.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="customers.customer",
                    ),
                ),
            ],
            options={
                "ordering": ["-occurred_at", "-id"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("account__isnull", True), ("customer__isnull", False)
                            ),
                            models.Q(
                                ("account__isnull", False), ("customer__isnull", True)
                            ),
                            _connector="OR",
                        ),
                        name="activity_belongs_to_exactly_one_parent",
                    )
                ],
            },
        ),
    ]
