# Generated by Django 5.2.17 on 2026-09-02 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0005_activity"),
    ]

    operations = [
        migrations.CreateModel(
            name="Email",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(max_length=255)),
                ("sender_name", models.CharField(max_length=150)),
                ("recipient_name", models.CharField(max_length=150)),
                (
                    "body",
                    models.TextField(
                        help_text="The summarized preview shown on the card."
                    ),
                ),
                ("sent_at", models.DateTimeField()),
                (
                    "links",
                    models.PositiveIntegerField(
                        default=0, help_text="Count shown on the card's link icon."
                    ),
                ),
                (
                    "watchers",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Count shown on the card's eye icon (views).",
                    ),
                ),
                ("is_starred", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "account",
                    models.ForeignKey(
                        blank=True,
                        help_text="Set for an account-level email. Exactly one of customer/account is set, never both — see the model's own CheckConstraint.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emails",
                        to="customers.account",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        help_text="Set for an organization-level email. Exactly one of customer/account is set, never both — see the model's own CheckConstraint.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emails",
                        to="customers.customer",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "emails",
                "ordering": ["-sent_at", "-id"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("account__isnull", True), ("customer__isnull", False)
                            ),
                            models.Q(
                                ("account__isnull", False), ("customer__isnull", True)
                            ),
                            _connector="OR",
                        ),
                        name="email_belongs_to_exactly_one_parent",
                    )
                ],
            },
        ),
    ]
