# Generated by Django 5.2.17 on 2026-09-02 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0007_task"),
    ]

    operations = [
        migrations.CreateModel(
            name="Note",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("author_name", models.CharField(max_length=150)),
                ("body", models.TextField()),
                ("logged_at", models.DateField()),
                (
                    "links",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Count shown on the card's link line — only rendered when > 0.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "account",
                    models.ForeignKey(
                        blank=True,
                        help_text="Set for an account-level note. Exactly one of customer/account is set, never both — see the model's own CheckConstraint.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="customers.account",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        help_text="Set for an organization-level note. Exactly one of customer/account is set, never both — see the model's own CheckConstraint.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="customers.customer",
                    ),
                ),
            ],
            options={
                "ordering": ["-logged_at", "-id"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("account__isnull", True), ("customer__isnull", False)
                            ),
                            models.Q(
                                ("account__isnull", False), ("customer__isnull", True)
                            ),
                            _connector="OR",
                        ),
                        name="note_belongs_to_exactly_one_parent",
                    )
                ],
            },
        ),
    ]
