# Generated by Django 5.2.17 on 2026-09-02 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0009_ticket"),
    ]

    operations = [
        migrations.CreateModel(
            name="CalendarEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.CharField(max_length=500)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("meeting", "Meeting"),
                            ("call", "Call"),
                            ("review", "Review"),
                            ("demo", "Demo"),
                        ],
                        max_length=8,
                    ),
                ),
                ("event_date", models.DateField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                (
                    "attendee_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text='Shown on the card as "N attendees" — not a list of names.',
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "account",
                    models.ForeignKey(
                        blank=True,
                        help_text="Set for an account-level event. Exactly one of customer/account is set, never both — see the model's own CheckConstraint.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calendar_events",
                        to="customers.account",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        help_text="Set for an organization-level event. Exactly one of customer/account is set, never both — see the model's own CheckConstraint.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calendar_events",
                        to="customers.customer",
                    ),
                ),
            ],
            options={
                "ordering": ["-event_date", "start_time", "-id"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("account__isnull", True), ("customer__isnull", False)),
                            models.Q(("account__isnull", False), ("customer__isnull", True)),
                            _connector="OR",
                        ),
                        name="calendarevent_belongs_to_exactly_one_parent",
                    )
                ],
            },
        ),
    ]
