# Generated by Django 5.2.17 on 2026-09-02 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0010_calendarevent"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="address",
            field=models.CharField(
                blank=True,
                help_text="Falls back to the parent customer's address (Overview's Location) when blank.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="email",
            field=models.EmailField(
                blank=True,
                help_text="Falls back to the parent customer's email (Overview) when blank.",
                max_length=254,
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="phone",
            field=models.CharField(
                blank=True,
                help_text="Falls back to the parent customer's phone (Overview) when blank.",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="email",
            field=models.EmailField(
                blank=True,
                help_text="Primary contact email, shown on Overview.",
                max_length=254,
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="phone",
            field=models.CharField(
                blank=True,
                help_text="Primary contact phone, shown on Overview.",
                max_length=32,
            ),
        ),
    ]
