# Generated by Django 5.2.17 on 2026-09-03 05:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0011_account_address_account_email_account_phone_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("executive_sponsor", "Executive Sponsor"),
                            ("champion", "Champion"),
                            ("economic_buyer", "Economic Buyer"),
                            ("technical_lead", "Technical Lead"),
                            ("decision_maker", "Decision Maker"),
                            ("influencer", "Influencer"),
                            ("finance_manager", "Finance Manager"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=32,
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=32)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive")],
                        default="active",
                        max_length=16,
                    ),
                ),
                (
                    "sentiment",
                    models.CharField(
                        choices=[
                            ("positive", "Positive"),
                            ("neutral", "Neutral"),
                            ("negative", "Negative"),
                        ],
                        default="neutral",
                        max_length=16,
                    ),
                ),
                (
                    "last_contacted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Formatted as relative time ('2 hours ago') on the frontend.",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "account",
                    models.ForeignKey(
                        blank=True,
                        help_text="Set for an account-level contact. Exactly one of customer/account is set, never both — see the model's own CheckConstraint.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contacts",
                        to="customers.account",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        help_text="Set for an organization-level contact. Exactly one of customer/account is set, never both — see the model's own CheckConstraint.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contacts",
                        to="customers.customer",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "contacts",
                "ordering": ["name"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("account__isnull", True), ("customer__isnull", False)
                            ),
                            models.Q(
                                ("account__isnull", False), ("customer__isnull", True)
                            ),
                            _connector="OR",
                        ),
                        name="contact_belongs_to_exactly_one_parent",
                    )
                ],
            },
        ),
    ]
