# Generated by Django 5.2.17 on 2026-09-04 17:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0017_remove_account_customer"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="currency",
            field=models.CharField(
                choices=[
                    ("USD", "US Dollar ($)"),
                    ("EUR", "Euro (€)"),
                    ("GBP", "British Pound (£)"),
                    ("INR", "Indian Rupee (₹)"),
                    ("CAD", "Canadian Dollar (C$)"),
                    ("AUD", "Australian Dollar (A$)"),
                    ("JPY", "Japanese Yen (¥)"),
                ],
                default="USD",
                help_text="The currency this customer's own contract/financial fields below are denominated in — independent of Organisation.currency, the tenant's own reporting currency. Defaults to the org's currency at creation (see CustomerSerializer.create()) but can differ from it, e.g. a US-HQ org billing one customer in EUR. Rollups that sum across customers with different currencies convert via services.fx_rates.conversion.convert_to_org_currency().",
                max_length=3,
            ),
        ),
    ]
