# Generated by Django 5.2.17 on 2026-09-05 02:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0018_customer_currency"),
    ]

    operations = [
        migrations.CreateModel(
            name="Survey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "survey_type",
                    models.CharField(
                        choices=[("nps", "NPS"), ("csat", "CSAT"), ("ces", "CES")],
                        max_length=8,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("sent", "Sent"),
                            ("responded", "Responded"),
                            ("expired", "Expired"),
                        ],
                        default="sent",
                        max_length=16,
                    ),
                ),
                (
                    "score",
                    models.IntegerField(
                        blank=True,
                        help_text="-100..100 for NPS, 0..100 for CSAT/CES. Required once status=RESPONDED (validated in the serializer, which also range-checks it against survey_type).",
                        null=True,
                    ),
                ),
                ("sent_at", models.DateField()),
                ("responded_at", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "account",
                    models.ForeignKey(
                        blank=True,
                        help_text="Set for an account-level survey. Exactly one of customer/account is set, never both — see the model's own CheckConstraint. Never set together with survey_type=CES — see the model's own docstring.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="surveys",
                        to="customers.account",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        help_text="Set for an organization-level survey. Exactly one of customer/account is set, never both — see the model's own CheckConstraint.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="surveys",
                        to="customers.customer",
                    ),
                ),
            ],
            options={
                "ordering": ["-sent_at", "-id"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("account__isnull", True), ("customer__isnull", False)),
                            models.Q(("account__isnull", False), ("customer__isnull", True)),
                            _connector="OR",
                        ),
                        name="survey_belongs_to_exactly_one_parent",
                    )
                ],
            },
        ),
    ]
