# Generated by Django 5.2.17 on 2026-09-05 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0001_initial"),
        ("customers", "0020_canvas"),
    ]

    operations = [
        migrations.AddField(
            model_name="email",
            name="campaign",
            field=models.ForeignKey(
                blank=True,
                help_text="Set only when this row was created by a real Campaign send.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="emails",
                to="campaigns.campaign",
            ),
        ),
    ]
