# Generated by Django 5.2.17 on 2026-09-05 13:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0021_email_campaign"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="industry",
            field=models.CharField(
                blank=True,
                help_text="Falls back to the parent customer's industry when blank — same convention as domain/address/email/phone below. See Customer.industry's own help_text for what this is actually for.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="industry",
            field=models.CharField(
                blank=True,
                help_text="Free-text, hand-entered (e.g. 'Video conferencing software'). Shown on Overview, and — the reason it exists — folded into what services/copilot/embeddings.py embeds for semantic company matching, so a company described but not named by its own name (e.g. 'that video conferencing account') can still be recognized once a CSM has actually filled this in; blank falls back to matching on the bare name alone, same as before this field existed.",
                max_length=255,
            ),
        ),
    ]
