# Generated by Django 5.2.17 on 2026-09-08 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0022_account_industry_customer_industry"),
    ]

    operations = [
        migrations.CreateModel(
            name="Headline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("summary", "Summary"), ("headline", "Headline")],
                        default="headline",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField()),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("open", "Open"),
                            ("in_progress", "In Progress"),
                            ("closed", "Closed"),
                        ],
                        help_text="HEADLINE cards only — always blank for a SUMMARY, enforced by the model's own CheckConstraint.",
                        max_length=20,
                    ),
                ),
                (
                    "period_start",
                    models.DateField(
                        blank=True,
                        help_text="Start of the span the card covers.",
                        null=True,
                    ),
                ),
                (
                    "period_end",
                    models.DateField(
                        blank=True,
                        help_text="End of the span the card covers. Also what the card's group pill is derived from, so a HEADLINE meant to appear under a group heading needs this set.",
                        null=True,
                    ),
                ),
                (
                    "time_period_label",
                    models.CharField(
                        blank=True,
                        help_text="SUMMARY cards only — the rolling window in words ('Last 3 months'), which no pair of dates conveys on its own.",
                        max_length=100,
                    ),
                ),
                (
                    "data_sources",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of DataSource values actually read to write this card. Rendered in the footer only when non-empty.",
                    ),
                ),
                (
                    "generated_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Set when written by the model, null when hand-written — regeneration only replaces its own previous output.",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "account",
                    models.ForeignKey(
                        blank=True,
                        help_text="Set for an account-level headline. Exactly one of customer/account is set, never both — see the model's own CheckConstraint.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="headlines",
                        to="customers.account",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        help_text="Set for an organization-level headline. Exactly one of customer/account is set, never both — see the model's own CheckConstraint.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="headlines",
                        to="customers.customer",
                    ),
                ),
            ],
            options={
                "ordering": ["kind", "-period_end", "-id"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("account__isnull", True), ("customer__isnull", False)
                            ),
                            models.Q(
                                ("account__isnull", False), ("customer__isnull", True)
                            ),
                            _connector="OR",
                        ),
                        name="headline_belongs_to_exactly_one_parent",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("kind", "summary"), _negated=True),
                            ("status", ""),
                            _connector="OR",
                        ),
                        name="headline_summary_has_no_status",
                    ),
                ],
            },
        ),
    ]
