# Generated by Django 5.2.17 on 2026-09-10 03:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("connectors", "0001_initial"),
        ("customers", "0023_headline"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="connector",
            field=models.ForeignKey(
                blank=True,
                help_text="Where this ticket came from. Null means it was raised in Revenact itself, which is a real case rather than missing data — and SET_NULL so removing a connector doesn't delete real support history.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tickets",
                to="connectors.connector",
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="resolved_at",
            field=models.DateField(
                blank=True,
                help_text="When the work finished. Null while the ticket is still open. Without this neither average ticket lifetime nor resolution rate can be computed at all.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="sentiment",
            field=models.CharField(
                choices=[
                    ("positive", "Positive"),
                    ("neutral", "Neutral"),
                    ("negative", "Negative"),
                ],
                default="neutral",
                help_text="How the customer sounds in this ticket. Backs the Ticket Overview dashboard's positive/negative counts and its sentiment trend.",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "Open"),
                    ("in-progress", "In Progress"),
                    ("on-hold", "On Hold"),
                    ("resolved", "Resolved"),
                    ("closed", "Closed"),
                ],
                default="open",
                max_length=16,
            ),
        ),
    ]
