# Generated by Django 5.2.17 on 2026-09-11 11:51

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


# Reverse of Customer.AI_PULSE_THRESHOLDS. Kept as a literal here rather than
# imported from the model: a migration has to keep describing the schema as it
# was at this point in history, even after the model moves on.
CATEGORY_TO_VALUE = {
    "very_satisfied": 5,
    "satisfied": 4,
    "moderate": 3,
    "high_risk": 1,
}
VALUE_TO_CATEGORY = {5: "very_satisfied", 4: "satisfied", 3: "moderate", 1: "high_risk", 2: "high_risk"}


def category_to_value(apps, schema_editor):
    """Carry the existing category across to the number that replaces it.

    Runs between the AddField and the RemoveField below, so no row loses its
    AI pulse: every seeded Customer and Account already carries one of the four
    categories, and dropping the column first would discard all of them.
    """
    for model_name in ("Customer", "Account"):
        model = apps.get_model("customers", model_name)
        for category, value in CATEGORY_TO_VALUE.items():
            model.objects.filter(ai_pulse_score=category).update(ai_pulse_value=value)


def value_to_category(apps, schema_editor):
    """Reverse: rebuild the category column from the number."""
    for model_name in ("Customer", "Account"):
        model = apps.get_model("customers", model_name)
        model.objects.filter(ai_pulse_value__isnull=True).update(ai_pulse_score="")
        for value, category in VALUE_TO_CATEGORY.items():
            model.objects.filter(ai_pulse_value=value).update(ai_pulse_score=category)


class Migration(migrations.Migration):

    dependencies = [
        (
            "customers",
            "0024_ticket_connector_ticket_resolved_at_ticket_sentiment_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="ai_pulse_value",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="1-5, produced by the model. See Customer.ai_pulse_value.",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="csm_pulse_modified_at",
            field=models.DateTimeField(
                blank=True, help_text="See Customer.csm_pulse_modified_at.", null=True
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="csm_pulse_score",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="1-5, set by hand by the CSM. See Customer.csm_pulse_score.",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="ai_pulse_value",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="1-5, produced by the model. ai_pulse_score (the category) is derived from this, not stored — same reasoning as health_score/health_category. Null means the model hasn't scored this one yet, which is not the same as a 1.",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="csm_pulse_modified_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When csm_pulse_score was last changed. Not auto_now — it tracks the pulse specifically, not any edit to the row, so a stale CSM read stays visibly stale.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="csm_pulse_score",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="1-5, set by hand by the CSM who owns this. Deliberately the same scale as ai_pulse_value so the two are directly comparable — the gap between them is what the Health Overview's Divergence view reads. Null means the CSM hasn't rated it, which is not the same as a 1.",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
        migrations.CreateModel(
            name="HealthSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "captured_on",
                    models.DateField(
                        help_text="The date this reading is for. Month-end when backfilled, so a series of these lines up as monthly columns."
                    ),
                ),
                (
                    "health_score",
                    models.DecimalField(
                        decimal_places=1,
                        help_text="0.0-10.0 as it stood on captured_on. health_category is derived.",
                        max_digits=3,
                    ),
                ),
                (
                    "csm_pulse_score",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="1-5 as it stood on captured_on, or null if unrated then.",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "ai_pulse_value",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="1-5 as it stood on captured_on, or null if unscored then.",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "account",
                    models.ForeignKey(
                        blank=True,
                        help_text="Set for an account-level snapshot. Exactly one of customer/account is set, never both — see the model's own CheckConstraint.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="health_snapshots",
                        to="customers.account",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        help_text="Set for an organization-level snapshot. Exactly one of customer/account is set, never both — see the model's own CheckConstraint.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="health_snapshots",
                        to="customers.customer",
                    ),
                ),
            ],
            options={
                "ordering": ["captured_on", "id"],
                "indexes": [
                    models.Index(
                        fields=["customer", "captured_on"],
                        name="customers_h_custome_216e0b_idx",
                    ),
                    models.Index(
                        fields=["account", "captured_on"],
                        name="customers_h_account_3a520c_idx",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("account__isnull", True), ("customer__isnull", False)
                            ),
                            models.Q(
                                ("account__isnull", False), ("customer__isnull", True)
                            ),
                            _connector="OR",
                        ),
                        name="healthsnapshot_belongs_to_exactly_one_parent",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("customer__isnull", False)),
                        fields=("customer", "captured_on"),
                        name="healthsnapshot_one_per_customer_per_date",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("account__isnull", False)),
                        fields=("account", "captured_on"),
                        name="healthsnapshot_one_per_account_per_date",
                    ),
                ],
            },
        ),
        migrations.RunPython(category_to_value, value_to_category),
        migrations.RemoveField(
            model_name="account",
            name="ai_pulse_score",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="ai_pulse_score",
        ),
    ]
