# Generated by Django 5.2.17 on 2026-09-11 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0025_remove_account_ai_pulse_score_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="health_score_override",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                help_text="A score pinned by hand, overriding the rubric. Null means the score is whatever the components add up to. Kept as its own column rather than just writing health_score, so 'a human decided this' stays distinguishable from 'the maths happened to land here' — the popover says which, and clearing this returns the customer to the calculation.",
                max_digits=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="health_score",
            field=models.DecimalField(
                decimal_places=1,
                default=5.0,
                help_text="0.0-10.0. Maintained by recalculate_health() from the five components in health.py — or set straight from health_score_override when that is set. Stored rather than derived so the list endpoint can still order and filter on it in SQL. health_category is derived from it.",
                max_digits=3,
            ),
        ),
    ]
