# Generated by Django 5.2.17 on 2026-09-12 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("connectors", "0001_initial"),
        ("customers", "0026_customer_health_score_override_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="email",
            name="ai_area",
            field=models.CharField(
                blank=True,
                choices=[
                    ("product_growth", "Product & Growth"),
                    ("support_operations", "Support & Operations"),
                    ("customer_success", "Customer Success"),
                ],
                help_text="Which side of the business owns this conversation. Blank until something classifies it.",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="email",
            name="ai_category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("onboarding", "Onboarding"),
                    ("bug_report", "Bug Report"),
                    ("workflow_automation", "Workflow Automation"),
                    ("integration_support", "Integration Support"),
                    ("system_notification", "System Notification"),
                    ("account_management", "Account Management"),
                    ("feature_request", "Feature Request"),
                    ("customer_feedback", "Customer Feedback"),
                    ("reporting_analytics", "Reporting & Analytics"),
                    ("security_compliance", "Security & Compliance"),
                ],
                help_text="What kind of conversation this is.",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="email",
            name="ai_classified_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the taxonomy above was last written. Null means this row has never been classified, which is what classify_interactions looks for.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="email",
            name="ai_subcategory",
            field=models.CharField(
                blank=True,
                choices=[
                    ("setup_assistance", "Setup Assistance"),
                    ("training_request", "Training Request"),
                    ("data_import", "Data Import"),
                    ("performance_issue", "Performance Issue"),
                    ("backend_failure", "Backend Failure"),
                    ("ui_bug", "UI Bug"),
                    ("rule_misfire", "Rule Misfire"),
                    ("trigger_setup", "Trigger Setup"),
                    ("api_issue", "API Issue"),
                    ("webhook_failure", "Webhook Failure"),
                    ("third_party_connector", "Third-party Connector"),
                    ("alert_fatigue", "Alert Fatigue"),
                    ("notification_delivery", "Notification Delivery"),
                    ("email_delivery", "Email Delivery"),
                    ("plan_upgrade", "Plan Upgrade"),
                    ("user_access", "User Access"),
                    ("billing_question", "Billing Question"),
                    ("ui_enhancement", "UI Enhancement"),
                    ("new_integration", "New Integration"),
                    ("product_praise", "Product Praise"),
                    ("usability_feedback", "Usability Feedback"),
                    ("export_problem", "Export Problem"),
                    ("dashboard_request", "Dashboard Request"),
                    ("data_privacy", "Data Privacy"),
                    ("access_review", "Access Review"),
                ],
                help_text="The specific flavour. Must belong to ai_category — see taxonomy.SUBCATEGORIES_BY_CATEGORY.",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="email",
            name="sentiment",
            field=models.CharField(
                choices=[
                    ("positive", "Positive"),
                    ("neutral", "Neutral"),
                    ("negative", "Negative"),
                ],
                default="neutral",
                help_text="How the customer sounds here. Backs the AI Trending Topics dashboard's sentiment donut and trend line, and (for tickets) the Ticket Overview dashboard's own positive/negative counts.",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="ai_area",
            field=models.CharField(
                blank=True,
                choices=[
                    ("product_growth", "Product & Growth"),
                    ("support_operations", "Support & Operations"),
                    ("customer_success", "Customer Success"),
                ],
                help_text="Which side of the business owns this conversation. Blank until something classifies it.",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="ai_category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("onboarding", "Onboarding"),
                    ("bug_report", "Bug Report"),
                    ("workflow_automation", "Workflow Automation"),
                    ("integration_support", "Integration Support"),
                    ("system_notification", "System Notification"),
                    ("account_management", "Account Management"),
                    ("feature_request", "Feature Request"),
                    ("customer_feedback", "Customer Feedback"),
                    ("reporting_analytics", "Reporting & Analytics"),
                    ("security_compliance", "Security & Compliance"),
                ],
                help_text="What kind of conversation this is.",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="ai_classified_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the taxonomy above was last written. Null means this row has never been classified, which is what classify_interactions looks for.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="ai_subcategory",
            field=models.CharField(
                blank=True,
                choices=[
                    ("setup_assistance", "Setup Assistance"),
                    ("training_request", "Training Request"),
                    ("data_import", "Data Import"),
                    ("performance_issue", "Performance Issue"),
                    ("backend_failure", "Backend Failure"),
                    ("ui_bug", "UI Bug"),
                    ("rule_misfire", "Rule Misfire"),
                    ("trigger_setup", "Trigger Setup"),
                    ("api_issue", "API Issue"),
                    ("webhook_failure", "Webhook Failure"),
                    ("third_party_connector", "Third-party Connector"),
                    ("alert_fatigue", "Alert Fatigue"),
                    ("notification_delivery", "Notification Delivery"),
                    ("email_delivery", "Email Delivery"),
                    ("plan_upgrade", "Plan Upgrade"),
                    ("user_access", "User Access"),
                    ("billing_question", "Billing Question"),
                    ("ui_enhancement", "UI Enhancement"),
                    ("new_integration", "New Integration"),
                    ("product_praise", "Product Praise"),
                    ("usability_feedback", "Usability Feedback"),
                    ("export_problem", "Export Problem"),
                    ("dashboard_request", "Dashboard Request"),
                    ("data_privacy", "Data Privacy"),
                    ("access_review", "Access Review"),
                ],
                help_text="The specific flavour. Must belong to ai_category — see taxonomy.SUBCATEGORIES_BY_CATEGORY.",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="sentiment",
            field=models.CharField(
                choices=[
                    ("positive", "Positive"),
                    ("neutral", "Neutral"),
                    ("negative", "Negative"),
                ],
                default="neutral",
                help_text="How the customer sounds here. Backs the AI Trending Topics dashboard's sentiment donut and trend line, and (for tickets) the Ticket Overview dashboard's own positive/negative counts.",
                max_length=16,
            ),
        ),
        migrations.CreateModel(
            name="Call",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sentiment",
                    models.CharField(
                        choices=[
                            ("positive", "Positive"),
                            ("neutral", "Neutral"),
                            ("negative", "Negative"),
                        ],
                        default="neutral",
                        help_text="How the customer sounds here. Backs the AI Trending Topics dashboard's sentiment donut and trend line, and (for tickets) the Ticket Overview dashboard's own positive/negative counts.",
                        max_length=16,
                    ),
                ),
                (
                    "ai_area",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("product_growth", "Product & Growth"),
                            ("support_operations", "Support & Operations"),
                            ("customer_success", "Customer Success"),
                        ],
                        help_text="Which side of the business owns this conversation. Blank until something classifies it.",
                        max_length=32,
                    ),
                ),
                (
                    "ai_category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("onboarding", "Onboarding"),
                            ("bug_report", "Bug Report"),
                            ("workflow_automation", "Workflow Automation"),
                            ("integration_support", "Integration Support"),
                            ("system_notification", "System Notification"),
                            ("account_management", "Account Management"),
                            ("feature_request", "Feature Request"),
                            ("customer_feedback", "Customer Feedback"),
                            ("reporting_analytics", "Reporting & Analytics"),
                            ("security_compliance", "Security & Compliance"),
                        ],
                        help_text="What kind of conversation this is.",
                        max_length=32,
                    ),
                ),
                (
                    "ai_subcategory",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("setup_assistance", "Setup Assistance"),
                            ("training_request", "Training Request"),
                            ("data_import", "Data Import"),
                            ("performance_issue", "Performance Issue"),
                            ("backend_failure", "Backend Failure"),
                            ("ui_bug", "UI Bug"),
                            ("rule_misfire", "Rule Misfire"),
                            ("trigger_setup", "Trigger Setup"),
                            ("api_issue", "API Issue"),
                            ("webhook_failure", "Webhook Failure"),
                            ("third_party_connector", "Third-party Connector"),
                            ("alert_fatigue", "Alert Fatigue"),
                            ("notification_delivery", "Notification Delivery"),
                            ("email_delivery", "Email Delivery"),
                            ("plan_upgrade", "Plan Upgrade"),
                            ("user_access", "User Access"),
                            ("billing_question", "Billing Question"),
                            ("ui_enhancement", "UI Enhancement"),
                            ("new_integration", "New Integration"),
                            ("product_praise", "Product Praise"),
                            ("usability_feedback", "Usability Feedback"),
                            ("export_problem", "Export Problem"),
                            ("dashboard_request", "Dashboard Request"),
                            ("data_privacy", "Data Privacy"),
                            ("access_review", "Access Review"),
                        ],
                        help_text="The specific flavour. Must belong to ai_category — see taxonomy.SUBCATEGORIES_BY_CATEGORY.",
                        max_length=32,
                    ),
                ),
                (
                    "ai_classified_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the taxonomy above was last written. Null means this row has never been classified, which is what classify_interactions looks for.",
                        null=True,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text='e.g. "EMEA Retail - Renewal Readiness".',
                        max_length=255,
                    ),
                ),
                (
                    "host_name",
                    models.CharField(help_text="Who ran the call.", max_length=150),
                ),
                ("occurred_at", models.DateTimeField()),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Null when the recorder didn't report one — an unknown length, which is not the same as a zero-minute call.",
                        null=True,
                    ),
                ),
                (
                    "summary",
                    models.TextField(
                        blank=True,
                        help_text="The recap shown on the CallSense card. Blank for a call nobody has summarised.",
                    ),
                ),
                (
                    "links",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Count shown on the card's link line — only rendered when > 0.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "account",
                    models.ForeignKey(
                        blank=True,
                        help_text="Set for an account-level call. Exactly one of customer/account is set, never both — see the model's own CheckConstraint.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calls",
                        to="customers.account",
                    ),
                ),
                (
                    "connector",
                    models.ForeignKey(
                        blank=True,
                        help_text="The recorder this call came from. Null means it was logged by hand in Revenact, a real case rather than missing data — and SET_NULL so removing a connector doesn't delete call history.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="calls",
                        to="connectors.connector",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        help_text="Set for an organization-level call. Exactly one of customer/account is set, never both — see the model's own CheckConstraint.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calls",
                        to="customers.customer",
                    ),
                ),
            ],
            options={
                "ordering": ["-occurred_at", "-id"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("account__isnull", True), ("customer__isnull", False)),
                            models.Q(("account__isnull", False), ("customer__isnull", True)),
                            _connector="OR",
                        ),
                        name="call_belongs_to_exactly_one_parent",
                    )
                ],
            },
        ),
    ]
