# Generated by Django 5.2.17 on 2026-09-12 13:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0028_map_churn_reasons_to_choices"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="churn_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("price", "Price"),
                    ("budget", "Budget cut"),
                    ("product_gap", "Missing capability"),
                    ("adoption", "Never adopted"),
                    ("competitor", "Switched to a competitor"),
                    ("champion_left", "Champion left"),
                    ("acquired", "Acquired or merged"),
                    ("shut_down", "Went out of business"),
                    ("consolidation", "Vendor consolidation"),
                    ("support", "Service or support"),
                    ("other", "Other"),
                ],
                help_text="Why they left, from a closed list — blank means nobody recorded it, which is not the same as ChurnReason.OTHER. The detail goes in churn_comment; this field exists to be counted.",
                max_length=32,
            ),
        ),
    ]
