# Generated by Django 5.2.17 on 2026-09-12 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0033_primary_product_is_a_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="call",
            name="classification_corrected_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When a person last corrected the tags by hand. Set, the row is skipped by classify_interactions --reclassify: a correction outranks the model, and the next run must not quietly put the model's answer back. The correction itself is in metrics.Feedback.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="email",
            name="classification_corrected_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When a person last corrected the tags by hand. Set, the row is skipped by classify_interactions --reclassify: a correction outranks the model, and the next run must not quietly put the model's answer back. The correction itself is in metrics.Feedback.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="classification_corrected_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When a person last corrected the tags by hand. Set, the row is skipped by classify_interactions --reclassify: a correction outranks the model, and the next run must not quietly put the model's answer back. The correction itself is in metrics.Feedback.",
                null=True,
            ),
        ),
    ]
