# Generated by Django 5.2.17 on 2026-09-12 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0034_feedback_and_corrections"),
        ("metrics", "0007_explanation"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="initiative",
            field=models.ForeignKey(
                blank=True,
                help_text="The decision this work serves, if any — set when a proposal linked to an initiative is approved, so the initiative can show the work under it. SET_NULL: closing or deleting a decision does not delete the to-do.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tasks",
                to="metrics.initiative",
            ),
        ),
    ]
