# Generated by Django 5.2.17 on 2026-09-16 09:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0036_account_pulse_recorded_on"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="pulse_recorded_on",
            field=models.DateField(
                blank=True,
                help_text="The day the daily job last appended this customer's computed pulse category to `pulse` — see run_health_maintenance and pulse.py.",
                null=True,
            ),
        ),
    ]
