# Generated by Django 5.2.17 on 2026-09-16 10:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0037_customer_pulse_recorded_on"),
    ]

    operations = [
        migrations.AddField(
            model_name="email",
            name="direction",
            field=models.CharField(
                blank=True,
                choices=[("sent", "Sent"), ("received", "Received")],
                max_length=8,
            ),
        ),
        migrations.AddField(
            model_name="email",
            name="from_address",
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
