# Generated by Django 5.2.17 on 2026-09-16 10:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("campaigns", "0001_initial"),
        ("customers", "0038_mailbox"),
        ("mail", "0001_mailbox"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="email",
            name="mailbox",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="emails",
                to="mail.mailboxconnection",
            ),
        ),
        migrations.AddField(
            model_name="email",
            name="mailbox_owner",
            field=models.ForeignKey(
                blank=True,
                help_text="Whose mailbox this came through; decides who may read it.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="mailbox_emails",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="email",
            name="provider_message_id",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="email",
            name="synced_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="email",
            name="thread_id",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="email",
            name="to_addresses",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddIndex(
            model_name="email",
            index=models.Index(
                fields=["mailbox_owner", "-sent_at"],
                name="customers_e_mailbox_0cef6e_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="email",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("mailbox__isnull", False),
                    models.Q(("provider_message_id", ""), _negated=True),
                ),
                fields=("mailbox", "provider_message_id"),
                name="email_once_per_mailbox_message",
            ),
        ),
    ]
