# Generated by Django 5.2.17 on 2026-09-16 14:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("connectors", "0003_ticket_sources"),
        ("customers", "0041_task_people"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="department",
            field=models.CharField(blank=True, default="", max_length=16),
        ),
        migrations.AddField(
            model_name="ticket",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="ticket",
            name="external_id",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
        migrations.AddField(
            model_name="ticket",
            name="external_url",
            field=models.URLField(blank=True, default="", max_length=500),
        ),
        migrations.AddField(
            model_name="ticket",
            name="requester_email",
            field=models.EmailField(blank=True, default="", max_length=254),
        ),
        migrations.AddField(
            model_name="ticket",
            name="requester_name",
            field=models.CharField(blank=True, default="", max_length=150),
        ),
        migrations.AddField(
            model_name="ticket",
            name="synced_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name="ticket",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("connector__isnull", False),
                    models.Q(("external_id", ""), _negated=True),
                ),
                fields=("connector", "external_id"),
                name="ticket_unique_per_connector_external_id",
            ),
        ),
    ]
