# Generated by Django 5.2.17 on 2026-09-16 16:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0043_attachments_and_logged_calls"),
    ]

    operations = [
        migrations.AddField(
            model_name="call",
            name="participants",
            field=models.ManyToManyField(blank=True, related_name="calls", to="customers.contact"),
        ),
        migrations.AddField(
            model_name="contact",
            name="sentiment_computed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contact",
            name="sentiment_evidence",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="What the computed sentiment rests on: score, counts per kind and per sentiment, and when the latest interaction was.",
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="sentiment_source",
            field=models.CharField(
                choices=[
                    ("manual", "Set by hand"),
                    ("computed", "From their calls, emails and tickets"),
                ],
                default="manual",
                max_length=16,
            ),
        ),
    ]
