# Generated by Django 5.2.17 on 2026-09-16 17:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0044_contact_sentiment"),
    ]

    operations = [
        migrations.AddField(
            model_name="opportunity",
            name="department",
            field=models.CharField(blank=True, default="", max_length=16),
        ),
        migrations.AddField(
            model_name="risk",
            name="department",
            field=models.CharField(blank=True, default="", max_length=16),
        ),
    ]
