# Generated by Django 5.2.17 on 2026-09-23 07:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0046_email_thread_index"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="language",
            field=models.CharField(blank=True, default="", max_length=12),
        ),
    ]
