# Generated by Django 5.2.17 on 2026-09-28 14:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0047_translation_and_contact_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="call",
            name="not_analysable",
            field=models.BooleanField(
                default=False,
                help_text="Looked at, with nothing to judge: no transcript, no summary and a generic title, or the model declined it. `ai_classified_at` is set so no pass pays to retry it, and `sentiment` is not evidence of anything.",
            ),
        ),
    ]
