# Generated by Django 5.2.17 on 2026-09-30 17:26

import django.utils.timezone
from django.db import migrations, models


def backfill_stage_changed_at(apps, schema_editor):
    """Rows from before the stage clock have no stage history, so their clock
    starts when they were created (spec §2: "no data backfill beyond
    `stage_changed_at = created_at`"). Their dates stay empty."""
    for name in ("Opportunity", "Risk"):
        model = apps.get_model("customers", name)
        model.objects.update(stage_changed_at=models.F("created_at"))


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0048_call_not_analysable"),
    ]

    operations = [
        migrations.AddField(
            model_name="opportunity",
            name="expected_close",
            field=models.DateField(
                blank=True,
                help_text="When the deal is expected to close. Optional: an empty date reads 'No date' on the Pipelines page.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="opportunity",
            name="stage_changed_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                editable=False,
                help_text="When `stage` last changed, creation included. Kept by StageClockMixin; the Pipelines 'this quarter' tiles read it.",
            ),
        ),
        migrations.AddField(
            model_name="risk",
            name="due_by",
            field=models.DateField(
                blank=True,
                help_text="When the risk must be dealt with by. Optional: an empty date reads 'No date' on the Pipelines page.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="risk",
            name="stage_changed_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                editable=False,
                help_text="When `stage` last changed, creation included. Kept by StageClockMixin; the Pipelines 'this quarter' tiles read it.",
            ),
        ),
        migrations.AlterField(
            model_name="opportunity",
            name="stage",
            field=models.CharField(
                choices=[
                    ("discovery", "Discovery"),
                    ("qualification", "Qualification"),
                    ("solution_validation", "Solution Validation"),
                    ("proposal_price_review", "Proposal / Price Review"),
                    ("negotiation", "Negotiation"),
                    ("closed_won", "Closed Won"),
                    ("closed_lost", "Closed Lost"),
                ],
                default="discovery",
                max_length=32,
            ),
        ),
        migrations.RunPython(backfill_stage_changed_at, migrations.RunPython.noop),
    ]
