# Generated by Django 5.2.17 on 2026-09-06 06:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0003_organisation_ai_agent_enabled_and_more"),
        ("customers", "0022_account_industry_customer_industry"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomObjectDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("api_name", models.SlugField(max_length=255)),
                ("applies_to_customer", models.BooleanField(default=True)),
                ("applies_to_account", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_object_definitions",
                        to="accounts.organisation",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="CustomFieldDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("api_name", models.SlugField(max_length=255)),
                (
                    "field_type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("number", "Number"),
                            ("currency", "Currency"),
                            ("date", "Date"),
                            ("boolean", "Yes / No"),
                            ("picklist", "Picklist"),
                        ],
                        max_length=16,
                    ),
                ),
                ("is_required", models.BooleanField(default=False)),
                ("picklist_options", models.JSONField(blank=True, default=list)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "object_definition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fields",
                        to="custom_objects.customobjectdefinition",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="CustomObjectRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_object_records",
                        to="customers.account",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_object_records",
                        to="customers.customer",
                    ),
                ),
                (
                    "object_definition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="records",
                        to="custom_objects.customobjectdefinition",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="customobjectdefinition",
            constraint=models.UniqueConstraint(
                fields=("organisation", "api_name"),
                name="unique_custom_object_api_name_per_org",
            ),
        ),
        migrations.AddConstraint(
            model_name="customobjectdefinition",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("applies_to_customer", True),
                    ("applies_to_account", True),
                    _connector="OR",
                ),
                name="custom_object_applies_to_at_least_one_parent_type",
            ),
        ),
        migrations.AddConstraint(
            model_name="customfielddefinition",
            constraint=models.UniqueConstraint(
                fields=("object_definition", "api_name"),
                name="unique_custom_field_api_name_per_object",
            ),
        ),
        migrations.AddConstraint(
            model_name="customobjectrecord",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("account__isnull", True), ("customer__isnull", False)),
                    models.Q(("account__isnull", False), ("customer__isnull", True)),
                    _connector="OR",
                ),
                name="custom_object_record_belongs_to_exactly_one_parent",
            ),
        ),
    ]
