# Generated by Django 5.2.17 on 2026-09-21 13:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0013_totp_device"),
        ("identity", "0006_membership_owner"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.SlugField(max_length=40, unique=True)),
                ("name", models.CharField(max_length=80)),
                ("seats_included", models.PositiveIntegerField()),
                (
                    "monthly_credits",
                    models.PositiveIntegerField(help_text="Granted at each period start."),
                ),
                ("price_cents", models.PositiveIntegerField(default=0)),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("is_trial", models.BooleanField(default=False)),
                (
                    "is_public",
                    models.BooleanField(
                        default=True,
                        help_text="Offered to customers, not only assignable by staff.",
                    ),
                ),
                ("stripe_price_id", models.CharField(blank=True, max_length=120)),
                ("sort_order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["sort_order", "price_cents"],
            },
        ),
        migrations.CreateModel(
            name="BillingAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("trialing", "Trialing"),
                            ("active", "Active"),
                            ("past_due", "Past due"),
                            ("canceled", "Canceled"),
                        ],
                        default="trialing",
                        max_length=16,
                    ),
                ),
                ("seats_limit", models.PositiveIntegerField()),
                ("trial_ends_at", models.DateTimeField(blank=True, null=True)),
                ("current_period_end", models.DateTimeField(blank=True, null=True)),
                ("stripe_customer_id", models.CharField(blank=True, max_length=120)),
                (
                    "stripe_subscription_id",
                    models.CharField(blank=True, max_length=120),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organisation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="billing_account",
                        to="accounts.organisation",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="accounts",
                        to="billing.plan",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PaymentWebhookEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("provider", models.CharField(max_length=32)),
                ("event_id", models.CharField(max_length=160)),
                ("event_type", models.CharField(blank=True, max_length=80)),
                ("payload_sha256", models.CharField(blank=True, max_length=64)),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("outcome", models.CharField(blank=True, max_length=32)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("provider", "event_id"),
                        name="one_webhook_event_per_provider",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="CreditLedger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("grant", "Grant"),
                            ("consume", "Consume"),
                            ("refund", "Refund"),
                            ("adjust", "Adjustment"),
                            ("expire", "Expire"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "amount",
                    models.IntegerField(help_text="Signed: positive adds, negative removes."),
                ),
                ("balance_after", models.IntegerField()),
                ("reason", models.CharField(blank=True, max_length=255)),
                ("reference", models.CharField(blank=True, max_length=160)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ledger",
                        to="billing.billingaccount",
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["account", "created_at"],
                        name="billing_cre_account_773936_idx",
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("balance_after__gte", 0)),
                        name="credit_balance_never_negative",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("reference", ""), _negated=True),
                        fields=("account", "reference"),
                        name="one_ledger_row_per_reference",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SeatAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("allocated_at", models.DateTimeField(auto_now_add=True)),
                ("released_at", models.DateTimeField(blank=True, null=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seats",
                        to="billing.billingaccount",
                    ),
                ),
                (
                    "membership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seat_assignments",
                        to="identity.organizationmembership",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["account", "released_at"],
                        name="billing_sea_account_7a12e2_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("released_at__isnull", True)),
                        fields=("membership",),
                        name="one_open_seat_per_membership",
                    )
                ],
            },
        ),
    ]
