"""
URL configuration for the Revenact backend.

Structure:
- /admin/            Django admin
- /api/v1/...         Versioned API — every feature app mounts here as we build it
- /api/schema/        Raw OpenAPI 3 schema (JSON), auto-generated by drf-spectacular
- /api/docs/          Swagger UI — interactive API contract, browsable
- /api/redoc/         Redoc — read-only, cleaner reference view of the same schema
"""

from django.contrib import admin
from django.urls import include, path
from drf_spectacular.views import (
    SpectacularAPIView,
    SpectacularRedocView,
    SpectacularSwaggerView,
)

from services.customers.views import (
    AccountListView,
    AccountStatsView,
    CanvasDetailView,
    CanvasListView,
    CockpitSummaryView,
    ContactDetailView,
    ContactListView,
    ContactStatsView,
    OpportunityDetailView,
    OpportunityListView,
    RiskDetailView,
    RiskListView,
    SurveyDetailView,
    SurveyListView,
    TaskListView,
)

urlpatterns = [
    path("admin/", admin.site.urls),
    # API docs — the live, always-in-sync API contract.
    path("api/schema/", SpectacularAPIView.as_view(), name="schema"),
    path("api/docs/", SpectacularSwaggerView.as_view(url_name="schema"), name="swagger-ui"),
    path("api/redoc/", SpectacularRedocView.as_view(url_name="schema"), name="redoc"),
    # Feature apps mount here, one `include()` per app, as we build each one.
    # `accounts`/`customers` live at services/accounts/, services/customers/
    # (see config/settings.py's INSTALLED_APPS) — only the Python import
    # path changed, not the URL path or the app label these `include()`
    # calls' own `path()` prefixes and `name=` reverses still resolve by.
    path("api/v1/", include("core.urls")),
    # `accounts` app, mounted at /auth/ to match the frontend's features/auth/.
    path("api/v1/auth/", include("services.accounts.urls")),
    path("api/v1/customers/", include("services.customers.urls")),
    # Contact lives in the `customers` app (services/customers/models.py)
    # but is mounted at its own top-level /api/v1/contacts/ prefix rather
    # than nested under /customers/ — it's the one Contact view that spans
    # every Customer/Account at once (see ContactListView's own
    # docstring), unlike every other nested list under
    # services.customers.urls above.
    path("api/v1/contacts/stats/", ContactStatsView.as_view(), name="contact-stats"),
    path("api/v1/contacts/<int:pk>/", ContactDetailView.as_view(), name="contact-detail"),
    path("api/v1/contacts/", ContactListView.as_view(), name="contact-list"),
    # Opportunity, same reasoning as Contact above — mounted at its own
    # top-level /api/v1/opportunities/ prefix since it's the one
    # Opportunity view spanning every Customer/Account at once, unlike
    # the nested list-create endpoints under services.customers.urls.
    path(
        "api/v1/opportunities/<int:pk>/", OpportunityDetailView.as_view(), name="opportunity-detail"
    ),
    path("api/v1/opportunities/", OpportunityListView.as_view(), name="opportunity-list"),
    # Risk, same reasoning as Opportunity above — mounted at its own
    # top-level /api/v1/risks/ prefix since it's the one Risk view
    # spanning every Customer/Account at once, unlike the nested
    # list-create endpoints under services.customers.urls.
    path("api/v1/risks/<int:pk>/", RiskDetailView.as_view(), name="risk-detail"),
    path("api/v1/risks/", RiskListView.as_view(), name="risk-list"),
    # Survey, same reasoning as Opportunity/Risk above — mounted at its
    # own top-level /api/v1/surveys/ prefix since it's the one Survey
    # view spanning every Customer/Account at once (the standalone
    # Surveys page), unlike the nested list-create endpoints under
    # services.customers.urls (the Activity Feed's own Surveys filter).
    path("api/v1/surveys/<int:pk>/", SurveyDetailView.as_view(), name="survey-detail"),
    path("api/v1/surveys/", SurveyListView.as_view(), name="survey-list"),
    # Canvas, same reasoning as Survey above — mounted at its own
    # top-level /api/v1/canvases/ prefix since it's the one Canvas view
    # spanning every Customer/Account at once (the standalone Canvas
    # gallery), unlike the nested list-create endpoints under
    # services.customers.urls (the "Canvas List" Details-page tab).
    path("api/v1/canvases/<int:pk>/", CanvasDetailView.as_view(), name="canvas-detail"),
    path("api/v1/canvases/", CanvasListView.as_view(), name="canvas-list"),
    # Scenarios — its own app (services/scenarios/), unlike everything
    # above which lives in services.customers. Nothing here is nested
    # under a Customer/Account the way Task/Note/etc. are: a Scenario
    # isn't owned by one company, it's a tenant-wide automation.
    path("api/v1/scenarios/", include("services.scenarios.urls")),
    # Campaigns — its own app, same "tenant-wide, not owned by one
    # Customer/Account" reasoning as Scenarios above: a Campaign's
    # audience naturally spans many Customers/Accounts at once.
    path("api/v1/campaigns/", include("services.campaigns.urls")),
    # Webhooks — its own app, same "tenant-wide, not owned by one
    # Customer/Account" reasoning as Scenarios above.
    path("api/v1/webhooks/", include("services.webhooks.urls")),
    # Copilot — its own app, same "tenant-wide, not owned by one
    # Customer/Account" reasoning as Scenarios/Campaigns above; a
    # conversation is scoped to one User, not a Customer/Account.
    path("api/v1/copilot/", include("services.copilot.urls")),
    # FX rates — its own app, same "tenant-wide, admin-only-both-ways"
    # reasoning as Webhooks above (an exchange rate is financial config,
    # not everyday customer data).
    path("api/v1/fx-rates/", include("services.fx_rates.urls")),
    # Account, same top-level-prefix reasoning as Contact/Opportunity/Risk
    # above — the one Account view spanning every Customer at once. GET
    # only; there's no matching flat detail/create endpoint since "Add"/
    # "Edit" already have somewhere to go (the nested endpoints under
    # services.customers.urls) — see AccountListView's own docstring.
    path("api/v1/accounts/stats/", AccountStatsView.as_view(), name="account-stats"),
    path("api/v1/accounts/", AccountListView.as_view(), name="account-list"),
    # Task, same top-level-prefix reasoning as Contact/Opportunity/Risk
    # above — the one Task view spanning every Customer/Account at once.
    path("api/v1/tasks/", TaskListView.as_view(), name="task-list"),
    # Cockpit — its own top-level endpoint, not nested under any one app:
    # a real-data rollup spanning both Customer and Account, scoped to
    # the caller's own owned book of business. Powers Cockpit's own
    # "My Portfolio Summary"/"Renewals" tiles.
    path("api/v1/cockpit/summary/", CockpitSummaryView.as_view(), name="cockpit-summary"),
]
