"""
URL configuration for the Revenact backend.

Structure:
- /admin/            Django admin
- /api/v1/...         Versioned API — every feature app mounts here as we build it
- /api/schema/        Raw OpenAPI 3 schema (JSON), auto-generated by drf-spectacular
- /api/docs/          Swagger UI — interactive API contract, browsable
- /api/redoc/         Redoc — read-only, cleaner reference view of the same schema
"""

from django.contrib import admin
from django.urls import include, path
from drf_spectacular.views import (
    SpectacularAPIView,
    SpectacularRedocView,
    SpectacularSwaggerView,
)

from services.customers.communications_views import (
    CommunicationsListView,
    CommunicationsStatsView,
    EmailReplyView,
)
from services.customers.views import (
    AccountListView,
    AccountStatsView,
    CanvasDetailView,
    CanvasListView,
    CockpitSummaryView,
    ContactDetailView,
    ContactInteractionsView,
    ContactListView,
    ContactStatsView,
    FileDetailView,
    FileDownloadView,
    HeadlineDetailView,
    InteractionStatsView,
    OpportunityDetailView,
    OpportunityListView,
    ProductDetailView,
    ProductListView,
    RiskDetailView,
    RiskListView,
    SurveyDetailView,
    SurveyListView,
    TaskDetailView,
    TaskListView,
    TicketStatsView,
)
from services.metrics.views import ClassificationCorrectionView

urlpatterns = [
    path("admin/", admin.site.urls),
    # API docs — the live, always-in-sync API contract.
    path("api/schema/", SpectacularAPIView.as_view(), name="schema"),
    path("api/docs/", SpectacularSwaggerView.as_view(url_name="schema"), name="swagger-ui"),
    path("api/redoc/", SpectacularRedocView.as_view(url_name="schema"), name="redoc"),
    # Feature apps mount here, one `include()` per app, as we build each one.
    # `accounts`/`customers` live at services/accounts/, services/customers/
    # (see config/settings.py's INSTALLED_APPS) — only the Python import
    # path changed, not the URL path or the app label these `include()`
    # calls' own `path()` prefixes and `name=` reverses still resolve by.
    path("api/v1/", include("core.urls")),
    # `accounts` app, mounted at /auth/ to match the frontend's features/auth/.
    path("api/v1/auth/", include("services.accounts.urls")),
    # Sign-in with an external provider. Beside the password endpoints
    # rather than in place of them: both are live while AUTH_V2_ENABLED is
    # being rolled out (see services/identity/views.py).
    path("api/v1/auth/oauth/", include("services.identity.urls")),
    # Domains and access requests, scoped to the caller's own tenant.
    path("api/v1/identity/", include("services.identity.admin_urls")),
    # Revenact's own staff administering every tenant: superuser + second factor.
    path("api/v1/platform/", include("services.platform.urls")),
    # Seats, credits and plans, scoped to the caller's own tenant.
    path("api/v1/billing/", include("services.billing.urls")),
    path("api/v1/customers/", include("services.customers.urls")),
    # Product lives in the `customers` app but is mounted at its own
    # top-level prefix, for two reasons: it is organisation
    # configuration rather than one customer's sub-resource, and
    # /api/v1/customers/products/ already means the Product Usage
    # dashboard's rollup. Same treatment as Contact below.
    path("api/v1/products/<int:pk>/", ProductDetailView.as_view(), name="product-detail"),
    path("api/v1/products/", ProductListView.as_view(), name="product-list"),
    # Contact lives in the `customers` app (services/customers/models.py)
    # but is mounted at its own top-level /api/v1/contacts/ prefix rather
    # than nested under /customers/ — it's the one Contact view that spans
    # every Customer/Account at once (see ContactListView's own
    # docstring), unlike every other nested list under
    # services.customers.urls above.
    # Files: a row and its bytes are reached by id from any company's Files
    # tab, so they sit at their own prefix; both check the caller may open
    # the company the file hangs off (services/customers/views.py).
    path("api/v1/files/<int:pk>/", FileDetailView.as_view(), name="file-detail"),
    path("api/v1/files/<int:pk>/download/", FileDownloadView.as_view(), name="file-download"),
    path("api/v1/contacts/stats/", ContactStatsView.as_view(), name="contact-stats"),
    path("api/v1/contacts/<int:pk>/", ContactDetailView.as_view(), name="contact-detail"),
    path(
        "api/v1/contacts/<int:pk>/interactions/",
        ContactInteractionsView.as_view(),
        name="contact-interactions",
    ),
    path("api/v1/contacts/", ContactListView.as_view(), name="contact-list"),
    # Opportunity, same reasoning as Contact above — mounted at its own
    # top-level /api/v1/opportunities/ prefix since it's the one
    # Opportunity view spanning every Customer/Account at once, unlike
    # the nested list-create endpoints under services.customers.urls.
    path(
        "api/v1/opportunities/<int:pk>/", OpportunityDetailView.as_view(), name="opportunity-detail"
    ),
    path("api/v1/opportunities/", OpportunityListView.as_view(), name="opportunity-list"),
    # Risk, same reasoning as Opportunity above — mounted at its own
    # top-level /api/v1/risks/ prefix since it's the one Risk view
    # spanning every Customer/Account at once, unlike the nested
    # list-create endpoints under services.customers.urls.
    path("api/v1/risks/<int:pk>/", RiskDetailView.as_view(), name="risk-detail"),
    path("api/v1/risks/", RiskListView.as_view(), name="risk-list"),
    # Survey, same reasoning as Opportunity/Risk above — mounted at its
    # own top-level /api/v1/surveys/ prefix since it's the one Survey
    # view spanning every Customer/Account at once (the standalone
    # Surveys page), unlike the nested list-create endpoints under
    # services.customers.urls (the Activity Feed's own Surveys filter).
    path("api/v1/surveys/<int:pk>/", SurveyDetailView.as_view(), name="survey-detail"),
    path("api/v1/surveys/", SurveyListView.as_view(), name="survey-list"),
    # Canvas, same reasoning as Survey above — mounted at its own
    # top-level /api/v1/canvases/ prefix since it's the one Canvas view
    # spanning every Customer/Account at once (the standalone Canvas
    # gallery), unlike the nested list-create endpoints under
    # services.customers.urls (the "Canvas List" Details-page tab).
    path("api/v1/canvases/<int:pk>/", CanvasDetailView.as_view(), name="canvas-detail"),
    path("api/v1/canvases/", CanvasListView.as_view(), name="canvas-list"),
    # Headline detail only — unlike Survey/Canvas above there's no
    # cross-company Headline list, because there's no page that wants
    # one: a headline is only ever read in the context of the company
    # it summarises. This exists so a card's own edit/delete controls
    # have a route that doesn't require knowing which of the two
    # parent shapes the card came from.
    path("api/v1/headlines/<int:pk>/", HeadlineDetailView.as_view(), name="headline-detail"),
    # Scenarios — its own app (services/scenarios/), unlike everything
    # above which lives in services.customers. Nothing here is nested
    # under a Customer/Account the way Task/Note/etc. are: a Scenario
    # isn't owned by one company, it's a tenant-wide automation.
    path("api/v1/scenarios/", include("services.scenarios.urls")),
    # Campaigns — its own app, same "tenant-wide, not owned by one
    # Customer/Account" reasoning as Scenarios above: a Campaign's
    # audience naturally spans many Customers/Accounts at once.
    path("api/v1/campaigns/", include("services.campaigns.urls")),
    # Webhooks — its own app, same "tenant-wide, not owned by one
    # Customer/Account" reasoning as Scenarios above.
    path("api/v1/webhooks/", include("services.webhooks.urls")),
    # Copilot — its own app, same "tenant-wide, not owned by one
    # Customer/Account" reasoning as Scenarios/Campaigns above; a
    # conversation is scoped to one User, not a Customer/Account.
    path("api/v1/copilot/", include("services.copilot.urls")),
    # Notifications — its own app, same "tenant-wide, not owned by one
    # Customer/Account" reasoning as Scenarios/Campaigns/Copilot above;
    # a notification is scoped to one User (its own recipient), not a
    # Customer/Account. Powers the Navbar's own real bell dropdown.
    path("api/v1/notifications/", include("services.notifications.urls")),
    # Custom Objects — its own app, same "tenant-wide, not owned by one
    # Customer/Account" reasoning as the above; unlike those, a custom
    # object *definition* is org-wide config (see IsOrgAdmin gating in
    # its own views.py) while its *records* each belong to exactly one
    # Customer or Account, same shape as Opportunity/Risk/etc.
    path("api/v1/custom-objects/", include("services.custom_objects.urls")),
    path("api/v1/attributes/", include("services.attributes.urls")),
    path("api/v1/requests/", include("services.requests.urls")),
    path("api/v1/anomalies/", include("services.anomalies.urls")),
    path("api/v1/translations/", include("services.translation.urls")),
    path("api/v1/mcp/", include("services.mcp.urls")),
    # The Organizations page's own endpoint (list, export, bulk). /customers/
    # stays as it is for its other consumers — see services/organizations.
    path("api/v1/organizations/", include("services.organizations.urls")),
    # FX rates — its own app, same "tenant-wide, admin-only-both-ways"
    # reasoning as Webhooks above (an exchange rate is financial config,
    # not everyday customer data).
    path("api/v1/fx-rates/", include("services.fx_rates.urls")),
    # The metric layer: every headline number defined once, whole-org, with
    # month-end history. Gated on view_all_accounts — see services/metrics.
    path("api/v1/metrics/", include("services.metrics.urls")),
    path("api/v1/", include("services.knowledge.urls")),
    path("api/v1/", include("services.mail.urls")),
    # A person correcting the model's tags on one interaction. Lives with the
    # feedback log it writes to, mounted beside the interactions stats.
    path(
        "api/v1/interactions/<str:kind>/<int:pk>/classification/",
        ClassificationCorrectionView.as_view(),
        name="interaction-classification",
    ),
    # Connectors — the external systems an organisation has hooked up
    # (Zendesk, Jira, ...). Same "tenant-wide config, not owned by one
    # Customer/Account" reasoning as Webhooks and FX rates above, with
    # one difference: reads are open to any member, because the Ticket
    # Overview dashboard labels its origin chart with connector names.
    path("api/v1/connectors/", include("services.connectors.urls")),
    # Account, same top-level-prefix reasoning as Contact/Opportunity/Risk
    # above — the one Account view spanning every Customer at once. GET
    # only; there's no matching flat detail/create endpoint since "Add"/
    # "Edit" already have somewhere to go (the nested endpoints under
    # services.customers.urls) — see AccountListView's own docstring.
    path("api/v1/accounts/stats/", AccountStatsView.as_view(), name="account-stats"),
    path("api/v1/accounts/", AccountListView.as_view(), name="account-list"),
    # Task, same top-level-prefix reasoning as Contact/Opportunity/Risk
    # above — the one Task view spanning every Customer/Account at once.
    path("api/v1/tasks/", TaskListView.as_view(), name="task-list"),
    path("api/v1/tasks/<int:pk>/", TaskDetailView.as_view(), name="task-detail"),
    # Ticket rollups for the Ticket Overview dashboard. A stats-only
    # endpoint with no matching list — a flat "every ticket" list has
    # no consumer, and the dashboard only ever wants the aggregates.
    path("api/v1/tickets/stats/", TicketStatsView.as_view(), name="ticket-stats"),
    # Interaction rollups for the AI Trending Topics dashboard. Its own
    # top-level prefix rather than a nest under /customers/ or /tickets/:
    # an "interaction" spans three models (Email, Call, Ticket) and every
    # Customer/Account at once, so it belongs under neither. Stats-only,
    # same reasoning as tickets above — the dashboard wants aggregates,
    # and each record type already has its own scoped list endpoint for
    # the Activity Feed.
    path("api/v1/interactions/stats/", InteractionStatsView.as_view(), name="interaction-stats"),
    # Cockpit — its own top-level endpoint, not nested under any one app:
    # a real-data rollup spanning both Customer and Account, scoped to
    # the caller's own owned book of business. Powers Cockpit's own
    # "My Portfolio Summary"/"Renewals" tiles.
    path("api/v1/cockpit/summary/", CockpitSummaryView.as_view(), name="cockpit-summary"),
    # Communications — the queue of what is waiting on the caller, merged
    # across four models (Email, Question, Ticket, Call). Its own top-level
    # prefix for the same reason interactions has one: it belongs to no single
    # record type, and every per-record list already lives under its parent.
    path(
        "api/v1/communications/stats/",
        CommunicationsStatsView.as_view(),
        name="communications-stats",
    ),
    path("api/v1/communications/", CommunicationsListView.as_view(), name="communications-list"),
    path(
        "api/v1/communications/emails/<int:pk>/reply/",
        EmailReplyView.as_view(),
        name="communications-email-reply",
    ),
    # The Dashboard Overview's "Needs attention" list and per-user snoozing —
    # its own app (services/attention/) since it reads across Customer,
    # Ticket and Anomaly rather than belonging to any one of them.
    path("api/v1/dashboard/", include("services.attention.urls")),
]
