"""
URL configuration for the Revenact backend.

Structure:
- /admin/            Django admin
- /api/v1/...         Versioned API — every feature app mounts here as we build it
- /api/schema/        Raw OpenAPI 3 schema (JSON), auto-generated by drf-spectacular
- /api/docs/          Swagger UI — interactive API contract, browsable
- /api/redoc/         Redoc — read-only, cleaner reference view of the same schema
"""

from django.contrib import admin
from django.urls import include, path
from drf_spectacular.views import (
    SpectacularAPIView,
    SpectacularRedocView,
    SpectacularSwaggerView,
)

urlpatterns = [
    path("admin/", admin.site.urls),
    # API docs — the live, always-in-sync API contract.
    path("api/schema/", SpectacularAPIView.as_view(), name="schema"),
    path("api/docs/", SpectacularSwaggerView.as_view(url_name="schema"), name="swagger-ui"),
    path("api/redoc/", SpectacularRedocView.as_view(url_name="schema"), name="redoc"),
    # Feature apps mount here, one `include()` per app, as we build each one.
    # `accounts`/`customers` live at services/accounts/, services/customers/
    # (see config/settings.py's INSTALLED_APPS) — only the Python import
    # path changed, not the URL path or the app label these `include()`
    # calls' own `path()` prefixes and `name=` reverses still resolve by.
    path("api/v1/", include("core.urls")),
    # `accounts` app, mounted at /auth/ to match the frontend's features/auth/.
    path("api/v1/auth/", include("services.accounts.urls")),
    path("api/v1/customers/", include("services.customers.urls")),
]
