# Generated by Django 5.2.17 on 2026-08-31 16:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "health_score",
                    models.PositiveSmallIntegerField(
                        default=50,
                        help_text="0-100. health_category is derived from this, not stored.",
                    ),
                ),
                (
                    "arr",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Annual recurring revenue, in dollars.",
                        max_digits=12,
                    ),
                ),
                ("renewal_date", models.DateField(blank=True, null=True)),
                (
                    "lifecycle_stage",
                    models.CharField(
                        choices=[
                            ("onboarding", "Onboarding"),
                            ("kickoff", "Kickoff"),
                            ("adoption", "Adoption"),
                            ("live", "Live"),
                            ("renewal", "Renewal"),
                            ("churn", "Churn"),
                            ("expansion", "Expansion"),
                            ("other", "Other"),
                        ],
                        default="onboarding",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customers",
                        to="accounts.organisation",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        help_text="The CSM (or admin) assigned to this customer. Must be in the same organisation.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owned_customers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
