# Generated by Django 5.2.17 on 2026-08-31 16:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="arr",
        ),
        migrations.AddField(
            model_name="customer",
            name="additional_products_count",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="address",
            field=models.CharField(
                blank=True, help_text='"Name / Address" column.', max_length=255
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="ai_pulse_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="ai_pulse_score",
            field=models.CharField(
                blank=True,
                choices=[
                    ("very_satisfied", "Very Satisfied"),
                    ("satisfied", "Satisfied"),
                    ("moderate", "Moderate"),
                    ("high_risk", "High Risk"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="arr_billed_at_account",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="customer",
            name="arr_billed_at_hq",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="customer",
            name="ces_percentage",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="0-100 (%).",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="churn_comment",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="churn_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="churn_reason",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="customer",
            name="contract_end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="contract_start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="csat_score",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="0-100 (%).",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="domain",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="customer",
            name="implementation_fee",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="customer",
            name="joined_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="modified_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="nps_score",
            field=models.IntegerField(blank=True, help_text="-100 to 100.", null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="primary_product",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="customer",
            name="pulse",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Recent pulse-history dots, e.g. [1,1,0,2,1].",
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="scope_web_app",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="customer",
            name="top_source_channel",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="customer",
            name="total_active_seats",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="total_contract_value",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="customer",
            name="total_contracted_seats",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="total_forecasted_renewal_revenue",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="customer",
            name="total_hires",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="customer",
            name="health_score",
            field=models.DecimalField(
                decimal_places=1,
                default=5.0,
                help_text="0.0-10.0. health_category is derived from this, not stored.",
                max_digits=3,
            ),
        ),
    ]
