# Generated by Django 5.2.17 on 2026-09-23 06:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0013_totp_device"),
        ("customers", "0046_email_thread_index"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Anomaly",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("summary", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("live", "Live"),
                            ("acknowledged", "Acknowledged"),
                            ("resolved", "Resolved"),
                        ],
                        default="live",
                        max_length=16,
                    ),
                ),
                ("embedding", models.JSONField(blank=True, default=list)),
                ("first_seen_at", models.DateTimeField()),
                ("last_seen_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "acknowledged_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="anomalies",
                        to="accounts.organisation",
                    ),
                ),
            ],
            options={
                "ordering": ["-last_seen_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="AnomalyEvidence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("ticket", "Ticket"),
                            ("call", "Call"),
                        ],
                        max_length=8,
                    ),
                ),
                ("record_id", models.PositiveIntegerField()),
                ("snippet", models.CharField(max_length=500)),
                ("department", models.CharField(blank=True, default="", max_length=16)),
                ("occurred_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="anomaly_evidence",
                        to="customers.account",
                    ),
                ),
                (
                    "anomaly",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidence",
                        to="anomalies.anomaly",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="anomaly_evidence",
                        to="customers.customer",
                    ),
                ),
                (
                    "mailbox_owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="anomaly_evidence",
                        to="accounts.organisation",
                    ),
                ),
            ],
            options={
                "ordering": ["-occurred_at", "-id"],
            },
        ),
        migrations.AddIndex(
            model_name="anomaly",
            index=models.Index(
                fields=["organisation", "status", "-last_seen_at"],
                name="anomalies_a_organis_7374f7_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="anomalyevidence",
            constraint=models.UniqueConstraint(
                fields=("kind", "record_id"), name="one_anomaly_filing_per_interaction"
            ),
        ),
        migrations.AddConstraint(
            model_name="anomalyevidence",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("account__isnull", True), ("customer__isnull", False)),
                    models.Q(("account__isnull", False), ("customer__isnull", True)),
                    _connector="OR",
                ),
                name="anomaly_evidence_belongs_to_exactly_one_parent",
            ),
        ),
    ]
