# Generated by Django 5.2.17 on 2026-09-22 17:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0013_totp_device"),
        ("customers", "0046_email_thread_index"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AIAttribute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("api_name", models.SlugField(max_length=255)),
                ("prompt", models.TextField()),
                (
                    "value_type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("number", "Number"),
                            ("boolean", "Yes / No"),
                            ("picklist", "Picklist"),
                        ],
                        default="text",
                        max_length=16,
                    ),
                ),
                ("picklist_options", models.JSONField(blank=True, default=list)),
                ("applies_to_customer", models.BooleanField(default=True)),
                ("applies_to_account", models.BooleanField(default=False)),
                (
                    "refresh",
                    models.CharField(
                        choices=[
                            ("manual", "When someone asks"),
                            ("nightly", "Nightly, when there is new activity"),
                        ],
                        default="manual",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_attributes",
                        to="accounts.organisation",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="AIAttributeValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.JSONField(blank=True, null=True)),
                ("reasoning", models.TextField(blank=True)),
                ("sources", models.JSONField(blank=True, default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("filled", "Filled"),
                            ("insufficient", "Not enough evidence"),
                            ("failed", "Failed"),
                        ],
                        default="filled",
                        max_length=16,
                    ),
                ),
                (
                    "origin",
                    models.CharField(
                        choices=[("ai", "AI"), ("human", "Person")],
                        default="ai",
                        max_length=8,
                    ),
                ),
                ("computed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_attribute_values",
                        to="customers.account",
                    ),
                ),
                (
                    "attribute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="values",
                        to="attributes.aiattribute",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_attribute_values",
                        to="customers.customer",
                    ),
                ),
                (
                    "set_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-computed_at", "-id"],
            },
        ),
        migrations.AddConstraint(
            model_name="aiattribute",
            constraint=models.UniqueConstraint(
                fields=("organisation", "api_name"),
                name="unique_ai_attribute_api_name_per_org",
            ),
        ),
        migrations.AddConstraint(
            model_name="aiattribute",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("applies_to_customer", True),
                    ("applies_to_account", True),
                    _connector="OR",
                ),
                name="ai_attribute_applies_to_at_least_one_parent_type",
            ),
        ),
        migrations.AddIndex(
            model_name="aiattributevalue",
            index=models.Index(
                fields=["attribute", "customer", "-computed_at"],
                name="attributes__attribu_3752b8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="aiattributevalue",
            index=models.Index(
                fields=["attribute", "account", "-computed_at"],
                name="attributes__attribu_fc1a33_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="aiattributevalue",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("account__isnull", True), ("customer__isnull", False)),
                    models.Q(("account__isnull", False), ("customer__isnull", True)),
                    _connector="OR",
                ),
                name="ai_attribute_value_belongs_to_exactly_one_parent",
            ),
        ),
    ]
