# Generated by Django 5.2.17 on 2026-10-03 09:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("campaigns", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaign",
            name="status",
            field=models.CharField(
                choices=[("draft", "Draft"), ("sending", "Sending"), ("sent", "Sent")],
                default="draft",
                max_length=8,
            ),
        ),
    ]
