# Generated by Django 5.2.17 on 2026-09-22 18:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0013_totp_device"),
        ("customers", "0046_email_thread_index"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FeatureRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("summary", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("planned", "Planned"),
                            ("shipped", "Shipped"),
                            ("declined", "Declined"),
                        ],
                        default="open",
                        max_length=16,
                    ),
                ),
                ("embedding", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feature_requests",
                        to="accounts.organisation",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owned_feature_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="RequestEvidence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("ticket", "Ticket"),
                            ("call", "Call"),
                        ],
                        max_length=8,
                    ),
                ),
                ("record_id", models.PositiveIntegerField()),
                ("snippet", models.CharField(max_length=500)),
                ("occurred_at", models.DateTimeField()),
                ("dismissed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="request_evidence",
                        to="customers.account",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="request_evidence",
                        to="customers.customer",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="request_evidence",
                        to="accounts.organisation",
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidence",
                        to="requests.featurerequest",
                    ),
                ),
            ],
            options={
                "ordering": ["-occurred_at", "-id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("kind", "record_id"), name="one_filing_per_interaction"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("account__isnull", True), ("customer__isnull", False)),
                            models.Q(("account__isnull", False), ("customer__isnull", True)),
                            _connector="OR",
                        ),
                        name="request_evidence_belongs_to_exactly_one_parent",
                    ),
                ],
            },
        ),
    ]
