# Generated by Django 5.2.17 on 2026-09-04 12:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="organisation",
            name="currency",
            field=models.CharField(
                choices=[
                    ("USD", "US Dollar ($)"),
                    ("EUR", "Euro (€)"),
                    ("GBP", "British Pound (£)"),
                    ("INR", "Indian Rupee (₹)"),
                    ("CAD", "Canadian Dollar (C$)"),
                    ("AUD", "Australian Dollar (A$)"),
                    ("JPY", "Japanese Yen (¥)"),
                ],
                default="USD",
                max_length=3,
            ),
        ),
        migrations.AddField(
            model_name="organisation",
            name="default_lifecycle_stage",
            field=models.CharField(
                blank=True,
                default="",
                help_text="One of Customer.LifecycleStage's own values, or blank for no tenant-wide default (see this model's own docstring).",
                max_length=16,
            ),
        ),
    ]
