# Generated by Django 5.2.17 on 2026-09-04 13:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_organisation_currency_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="organisation",
            name="ai_agent_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="organisation",
            name="ai_agent_tone",
            field=models.CharField(
                choices=[
                    ("professional", "Professional"),
                    ("friendly", "Friendly"),
                    ("concise", "Concise"),
                ],
                default="professional",
                max_length=16,
            ),
        ),
    ]
