# Generated by Django 5.2.17 on 2026-09-12 21:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0007_grant_view_all_accounts"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="function",
            field=models.CharField(
                choices=[
                    ("cs", "Customer Success"),
                    ("engineering", "Engineering"),
                    ("sales", "Sales"),
                    ("analytics", "Analytics"),
                    ("leadership", "Leadership"),
                    ("other", "Other"),
                ],
                default="cs",
                max_length=16,
            ),
        ),
    ]
