# Generated by Django 5.2.17 on 2026-09-12 22:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0008_knowledge"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="reports_to",
            field=models.ForeignKey(
                blank=True,
                help_text="Their manager — the org chart. What a person may see of what others say is read from it (services.accounts.hierarchy).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reports",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
