# Generated by Django 5.2.17 on 2026-09-13 12:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0009_org_chart"),
    ]

    operations = [
        migrations.AddField(
            model_name="organisation",
            name="global_attributes",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
