# Generated by Django 5.2.17 on 2026-09-20 07:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0010_global_attributes"),
    ]

    operations = [
        migrations.AddField(
            model_name="organisation",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("active", "Active"),
                    ("suspended", "Suspended"),
                    ("archived", "Archived"),
                ],
                default="active",
                help_text="Existing tenants are active; nothing reads this yet (phase 1).",
                max_length=16,
            ),
        ),
    ]
